### ISSUE TITLE
issues with failed getting changed files

### ISSUE THREAD

**Issue by daniel-xsu** [tj-actions/changed-files#100]
hi, 
I met the following errors when using git enterprise. btw, I use ssh login the git repo other than username/password. I changed other repo with .git subdirectory, it still complains the same error. I double checked my repo it works fine but still failed to get this github action works

error log:
================
Run tj-actions/changed-files@v7
  with:
    token: ***
    separator:  
/usr/bin/docker run --name fe336efc00c723f4a47d480e9c9a46f254d67_122cbd --label 6fe336 --workdir /github/workspace --rm -e INPUT_TOKEN -e INPUT_SEPARATOR -e INPUT_FILES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/daniel/actions-runner/_work/_temp/_github_home":"/github/home" -v "/home/daniel/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/home/daniel/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/daniel/actions-runner/_work/temp-repo-4-github-action/temp-repo-4-github-action":"/github/workspace" 6fe336:efc00c723f4a47d480e9c9a46f254d67
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

my .git/workflow/ci.yaml
==========
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  changedfiles:
    runs-on: [ self-hosted ]
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v7
      
      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

**Comment by jackton1** [comment]
Hi @daniel-xsu this issue doesn't follow the bug issue template.

Closing due to lack of proper description.
