### ISSUE TITLE
support windows-latest

### ISSUE THREAD

**Issue by Nambers** [tj-actions/changed-files#101]
**Is your feature request related to a problem? Please describe.**
uh yes, when i use this workflow in windows-latest env, it cause a error:
```
Run tj-actions/changed-files@v7
  with:
    token: ***
    separator:  
Error: Container action is only supported on Linux
```
And that is because i should run my C++ workflow in win to use msvc, and i want to use change-file together

**Describe the solution you'd like**
Add win support

**Comment by jackton1** [comment]
@Nambers This should be resolved in the latest release.

**Comment by Nambers** [comment]
ok thx
