### ISSUE TITLE
[Feature] Use Full SHA instead tag in nested actions calls

### ISSUE THREAD

**Issue by juanimcal-indx** [tj-actions/changed-files#1019]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Due to restrictions in my organization, we are unable to use your action as there are 2 actions used inside changed-files:
- [tj-actions/glob@v16](https://github.com/tj-actions/changed-files/blob/93b782be1f24e5fd45acb77028b82845e518558c/action.yml#L211)
- [tj-actions/json2file@v1](https://github.com/tj-actions/changed-files/blob/93b782be1f24e5fd45acb77028b82845e518558c/action.yml#L258)

The actions are referenced using a tag.

It's considered a good practice to avoid branches & tags, using **sha** instead to reference exact and unique references to the code of the action: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

### Describe the solution you'd like?

Reference internal action calls by full sha instead tag. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juanimcal-indx** [comment]
Thank you very much @jackton1

**Comment by jackton1** [comment]
Hi @juanimcal-indx I wanted to let you know that this change would be implemented for tags with the `-sec` suffix in which case you just need to add `-sec` suffix if you are referencing the tag or the sha.

See the [Versioning](https://github.com/tj-actions/changed-files#versioning) section of the docs for more details
