### ISSUE TITLE
[BUG] Error in GitHub Action dependencies tj-actions/glob and tj-actions/json2file

### ISSUE THREAD

**Issue by NLadib-PartnerAuchan** [tj-actions/changed-files#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

We are using the GitHub Action tj-actions/changed-files@v35 in our GitHub workflow, along with its dependencies tj-actions/glob@v16 and tj-actions/json2file@v1. We have whitelisted in our Organization/Entreprise these dependencies to ensure that the correct versions are used.

However, we recently encountered an error where the version of these dependencies were changed and replaced by their commits, causing our workflow to fail.

We kindly request that you fix this issue by providing specific tags for both the tj-actions/glob and tj-actions/json2file actions, so that we can ensure that the correct versions are used in our workflow.

Thank you for your attention to this matter.

### To Reproduce

We have identified an issue with the GitHub Action tj-actions/changed-files, which can be easily reproduced by whitelisting the versions of its dependencies tj-actions/glob@v16 and tj-actions/json2file@v1

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

To address this issue, we kindly request that version control and tagging be implemented for all dependencies used in the tj-actions/changed-files GitHub Action. This will allow us to more easily identify and use the correct versions of these dependencies in our workflows, ensuring compatibility and preventing errors.

### Relevant log output

```shell
Bad request - tj-actions/glob@cebfb084cdf62d72c5318b1b3595ac5a45ed022f and tj-actions/json2file@ee0fd2ce53e57fa50da61615cd644018eaf3ab6c are not allowed to be used
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YHallouard** [comment]
Encountered the same error in our Organization/Entreprise. Thanks you in advance for your work :)

**Comment by jackton1** [comment]
@YHallouard @NLadib-PartnerAuchan @AdilFIKRI @auguster This should be resolved in the latest version.

**Comment by NLadib-PartnerAuchan** [comment]
Thank you very much @jackton1
