### ISSUE TITLE
[BUG] Version wrongly specified in the examples.

### ISSUE THREAD

**Issue by albertoperdomo2** [tj-actions/changed-files#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

This is something minor, but the example actions contain a capital V when specifying the version of this action. It should be `v` instead of `V`. 

### To Reproduce

1. Run the example actions.
2. It fails.

### What OS are you seeing the problem on?

macos-latest or macos-10.15

### Expected behavior?

Run correctly. 

### Relevant log output

```shell
Unable to resolve action `tj-actions/changed-files@V35`, unable to find version `V35`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by albertoperdomo2** [comment]
I know, super simple stuff but just worth mentioning.

**Comment by jackton1** [comment]
@all-contributors please add @albertoperdomo2 for docs
