### ISSUE TITLE
Using this action internally in our organization- unable to resolve the actions used by this action.

### ISSUE THREAD

**Issue by SuganJoe** [tj-actions/changed-files#1080]
### Discussed in https://github.com/tj-actions/changed-files/discussions/1079

<div type='discussions-op-text'>

<sup>Originally posted by **SuganJoe** April 10, 2023</sup>
when trying to use this action internally, unable to resolve the actions used by this action. 
Note: this action is enabled to use internally.
Error:
Unable to resolve action `tj-actions/glob@v16.14`, repository not found on this server. If you want to use this action from [GitHub.com](http://github.com/), see the following documentation: https://docs.github.com/en/enterprise/admin/github-actions/managing-access-to-actions-from-githubcom. 
Unable to resolve action `tj-actions/json2file@v1.4.0`, repository not found on this server. If you want to use this action from [GitHub.com](http://github.com/), see the following documentation: https://docs.github.com/en/enterprise/admin/github-actions/managing-access-to-actions-from-githubcom</div>

**Comment by jackton1** [comment]
Hi @SuganJoe, are you asking a question or providing a solution as the documentation posted outlines how to enable third party actions.

https://docs.github.com/en/enterprise-server@3.8/admin/github-actions/managing-access-to-actions-from-githubcom/about-using-actions-in-your-enterprise#configuring-access-to-actions-on-githubcom
