### ISSUE TITLE
Major change in dependency version breaks workflow

### ISSUE THREAD

**Issue by auguster** [tj-actions/changed-files#1085]
We use enterprise whitelisting on our Github organisation for actions. We had some breakage on our workflows because the dependencies of v35 to tj-actions/glob changed to major version v17 and we only whilelisted v16.* in our organisation.

We hoped that a major change in dependency would imply a major version change in the action itself. Could you please explain the policy for your version management so we can adapt our action whitelisting policies accordingly ?

**Comment by jackton1** [comment]
Hi @auguster, Thank you for reaching out and sorry to hear that the latest version upgrade of [tj-actions/glob](https://github.com/tj-actions/glob) action resulted in breaking existing workflows. 

In general, our versioning policy follows semantic versioning, which means that a major version change indicates a significant breaking change, while a minor version change includes backward-compatible new features and bug fixes.

Regarding the specific case you mentioned, the dependency change from v16 to v17 of [tj-actions/glob](https://github.com/tj-actions/glob) does not introduce any direct breaking change. Therefore, it only resulted in a bump of the minor version. However, please note that this may not always be the case, as some dependency changes may introduce breaking changes that require a major version bump.

We recommend pinning the version of the [tj-actions/changed-files](https://github.com/tj-actions/changed-files) to the latest patch or alternatively using a version that implements security-hardening strategies.

See: https://github.com/tj-actions/changed-files#versioning for more information
