### ISSUE TITLE
[BUG] Don't fail on huge diffs if `write_output_files: true` is set

### ISSUE THREAD

**Issue by JavaScriptBach** [tj-actions/changed-files#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

If I generate a huge diff, the action will fail due to GitHub Actions limits:

```
An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/obsidian/obsidian'. Argument list too long
```

I get this error even if I set `write_output_files: true`. The issue is in https://github.com/tj-actions/changed-files/blob/main/get-changed-paths.sh, which is setting the output of `git diff` to GitHub variables even when they may not fit.

### To Reproduce

Run the action on a diff with e.g. 5000+ files changed.

### What OS are you seeing the problem on?

all

### Expected behavior?

If `write_output_files: true`, I would expect the action to succeed on arbitrarily large diffs, because the output is written to disk rather than returned as GitHub actions outputs. However, this doesn't happen because the implementation currently still depends on GitHub actions outputs. I would suggest making it so that if `write_output_files: true`, then all string output values (e.g. `added_files`, `copied_files`, etc.) are blank and the user should read the outputs from files instead.

### Relevant log output

```shell
See above.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by omer-za** [comment]
Status here?

**Comment by jackton1** [comment]
This would be resolved by the end of the week in a new version

**Comment by jackton1** [comment]
Hi @JavaScriptBach @omer-za, this bug has been fixed in the latest v36 release.
