### ISSUE TITLE
[BUG]Error: The request HttpClient.Timeout

### ISSUE THREAD

**Issue by krotofil** [tj-actions/changed-files#1102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

we get the following error message with every second run when downloading the resources.

download action repository 'tj-actions/changed-files@v35.8.0' (SHA:7ecfc6730dff8072d1cc5215a24cc9478f55264d)
Warning: Failed to download action 'https://api.github.com/repos/tj-actions/changed-files/tarball/7ecfc6730dff8072d1cc5215a24cc9478f55264d'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off 11.263 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/tj-actions/changed-files/tarball/7ecfc6730dff8072d1cc5215a24cc9478f55264d'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
Warning: Back off 17.973 seconds before retry.

### To Reproduce

see describe bug

### What OS are you seeing the problem on?

all

### Expected behavior?

see describe bug

### Relevant log output

```shell
see describe bug
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@krotofil Given that the error seems like an issue with [GitHub runner](https://github.com/actions/runner), I'll recommend reaching out to [Github support](https://support.github.com/request/actions?tags=hubberfy_actions) to report the issue or creating an issue [here](https://github.com/actions/runner).
