### ISSUE TITLE
[BUG] File is getting identified as renamed even though it is not from the context of the commits being compared

### ISSUE THREAD

**Issue by kishaningithub** [tj-actions/changed-files#1103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

File is getting identified as renamed even though it is not from the context of the commits being compared

### To Reproduce

I am running this as part of a PR comment workflow and hence i am passing `$base` and `$sha` explicitly. The value for base is the latest commit in the main branch and the value for sha is the latest commit in the PR branch.

- Create a commit which adds a file
- In the next commit move the file to another location
- Add some other file in the third commit
- Raise a PR and ensure that `$base`  is pointing to the tip of the main branch and `$sha` is pointing to the tip of the PR branch and ensure `include_all_old_new_renamed_files` option is set to `true`

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Given the file `environment_params.json` is not there in the main branch and is only present the PR branch it should be shown as an addition 

### Relevant log output

Upon debugging i saw the command `git log --name-status --ignore-submodules=all "$base".."$sha"` which is present [here](https://github.com/tj-actions/changed-files/blob/a611c4893298c6cc704368e0dff0c8756387ce85/get-changed-paths.sh#L137)

The main branch does not contain the file `environment_params.json` but in the PR it was first placed in `configs/environment_params.json` then moved to `configs/dev/environment_params.json` causing a rename

```
commit 753aff15e38e6f6feaac2bd81a78ffdbda2fab98 (HEAD -> 3890, origin/3890)
Date:   Thu Apr 27 14:52:44 2023 +0530

    Change3

A	scripts/sample.py

commit 1348f57e453852aff28681f9385c3066faa8b6f4
Date:   Wed Apr 26 18:59:01 2023 +0530

    Change 2

R100	configs/environment_params.json	configs/dev/environment_params.json

commit 2a3823f1f51ac4eb1bc2b554a2d1122d3e3e973c
Date:   Wed Apr 26 17:09:11 2023 +0530

    Change 1

A	configs/environment_params.json
```

If you observe the second commit contained a rename and the grep matched that

### Anything else?

I am not sure apart from `git log` what other methods exist to detect renames

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@kishaningithub I believe you’ve determined why it’s considered a rename. Given that this isn’t a bug i.e changing file locations are considered to be the same as renaming the file itself. As such this isn’t a bug but I presume a feature in which you want renames to only be considered if the file already exists in the target branch.

I’ll suggest creating a separate issue which highlights that instead.

**Comment by kishaningithub** [comment]
I still think this is a bug because in the feature branch you do the following

- add a file in a commit
- delete a same file in the next commit

and you run this action on the PR the file does not even get listed meaning there it is comparing the tip locations of main and PR branch which i think is correct, but renames do not see it like that it says if there is a rename for a file within the PR branch it lists it even though the comparison is against the tip of main and pr branch

**Comment by kishaningithub** [comment]
So instead of greppng from git log, in my opinion you should be grepping the output git diff to check for renames

for example

```
$ git diff --name-status main..<<branch>>
```

the above command actually gives the desired result for this case viz

```
A     configs/dev/environment_params.json
A	scripts/sample.py
```

Say if there was a rename from main to the feature branch (i renamed README.md to README_now.md)

```
R100    README.md       README_now.md
A     configs/dev/environment_params.json
A	scripts/sample.py
```

**Comment by kishaningithub** [comment]
just curious.. was there any reasoning `git log` was used for renames instead of `git diff` ?

**Comment by kishaningithub** [comment]
@jackton1 i still feel this to be a bug given the difference in behavior for added/modified/deleted files to renamed files. If you disagree i will raise this as a feature request

Thanks for creating this tool BTW!

**Comment by jackton1** [comment]
@kishaningithub I stand corrected, and yes git diff would be a more accurate solution in this case. I'll reopen this issue and push out a fix soon. Thanks for the hard work testing this.
