### ISSUE TITLE
fetch-depth should be fetch_depth in README.md

### ISSUE THREAD

**Issue by rick-kenna** [tj-actions/changed-files#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

In README.md, `fetch-depth` should be `fetch_depth`.  When using `fetch-depth`, a warning was issued:
```
Warning: Unexpected input(s) 'fetch-depth', valid inputs are ['separator', 'include_all_old_new_renamed_files', 'old_new_separator', 'old_new_files_separator', 'files_from_source_file', 'files', 'files_separator', 'files_ignore', 'files_ignore_separator', 'files_ignore_from_source_file', 'sha', 'base_sha', 'since', 'until', 'path', 'quotepath', 'diff_relative', 'dir_names', 'dir_names_max_depth', 'dir_names_exclude_root', 'json', 'json_raw_format', 'fetch_depth', 'since_last_remote_commit', 'write_output_files', 'output_dir', 'match_directories']
```
After changing it to `fetch_depth`, no warning was issued.  Please update README.md if this is correct.

### To Reproduce

1. GitHub actions
2. Use `fetch-depth`
3. Receive a Warning.

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

I expected no warning with following the documentation.

### Relevant log output

```shell
: Unexpected input(s) 'fetch-depth', valid inputs are ['separator', 'include_all_old_new_renamed_files', 'old_new_separator', 'old_new_files_separator', 'files_from_source_file', 'files', 'files_separator', 'files_ignore', 'files_ignore_separator', 'files_ignore_from_source_file', 'sha', 'base_sha', 'since', 'until', 'path', 'quotepath', 'diff_relative', 'dir_names', 'dir_names_max_depth', 'dir_names_exclude_root', 'json', 'json_raw_format', 'fetch_depth', 'since_last_remote_commit', 'write_output_files', 'output_dir', 'match_directories']
```

### Anything else?

No.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@rick-kenna To clear up any confusion `fetch-depth` in the documentation refers to setting up [`actions/checkout`](https://github.com/actions/checkout)

**Comment by rick-kenna** [comment]
Thank-you for the clarity.
