### ISSUE TITLE
[Feature] Get the content in deleted file

### ISSUE THREAD

**Issue by SamuelMolling** [tj-actions/changed-files#1122]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I have the following code

```
      - name: Use template for a deleted file
        if: steps.changed-files-dir-names.outputs.any_deleted == 'true'
        run: |
          for folder in ${{ steps.changed-files-dir-names.outputs.deleted_files }}; do
            mkdir -p $folder
            if [[ $folder =~ "app" ]]; then
              cp .github/templates/user/app/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "iam" ]]; then
              cp .github/templates/user/iam/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "postgres" ]]; then
              cp .github/templates/cluster/terragrunt.hcl $folder/terragrunt.hcl
              cp .github/templates/cluster/cluster.hcl $folder/../cluster.hcl
            fi
          done
```

I create templates for the files I'm deleting, with random values, but with the same structure. But I came across the situation that I need a value from the file that was deleted, to put in the template file.

### Describe the solution you'd like?

I wanted to create the file temporarily in a random directory, then I would cat that file to the other.

### Describe alternatives you've considered?

I haven't considered anything yet, I'm studying and seeing if there are other possibilities.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@SamuelMolling can you provide more details on the feature request?

**Comment by jackton1** [comment]
No response on a path forward or how this feature should be implemented and requires more information on the intended use.
