### ISSUE TITLE
[Feature] Get the content in deleted file

### ISSUE THREAD

**Issue by SamuelMolling** [tj-actions/changed-files#1134]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I have the following code
```
      - name: Use template for a deleted file
        if: steps.changed-files-dir-names.outputs.any_deleted == 'true'
        run: |
          for folder in ${{ steps.changed-files-dir-names.outputs.deleted_files }}; do
            mkdir -p $folder
            if [[ $folder =~ "app" ]]; then
              cp .github/templates/user/app/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "iam" ]]; then
              cp .github/templates/user/iam/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "postgres" ]]; then
              cp .github/templates/cluster/terragrunt.hcl $folder/terragrunt.hcl
              cp .github/templates/cluster/cluster.hcl $folder/../cluster.hcl
            fi
          done
```
I create templates for the files I'm deleting, with random values, but with the same structure. But I came across the situation that I need a value from the file that was deleted, to put in the template file.

### Describe the solution you'd like?

I wanted to create the file temporarily in a random directory, then I would cat that file to the other.

### Describe alternatives you've considered?

I haven't considered anything yet, I'm studying and seeing if there are other possibilities.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SamuelMolling** [comment]
@jackton1, I had not received notifications for this feature https://github.com/tj-actions/changed-files/issues/1122


Answering the question: Basically I would like to get the value of a deleted file or save it in some path temporarily.


I have a process that creates a template from deleted files, until then it worked. However, I reached a point where I need the internal value of a file to do the process correctly.

The idea is to pass two parameters:
deleted-file-path: <PATH>
list-files: <LIST>

list-deleted-files: would be the list in case you want to ignore some for example or add the one you pass only, I'm not sure which is better.

The deleted-file-path is where I want to save the file, in this case the default is where the file was deleted. I can get it from the parameter ```dir_names: "true"``` to use in the case below

```
       - name: Terragrunt Plan for Destroy
         id: planForDestroy
         run: |
           echo 'PLAN_OUTPUT<<EOF' >> $GITHUB_ENV
           for folder in ${{ steps.changed-files-dir-names.outputs.deleted_files }}; of
               terragrunt plan -destroy --terragrunt-working-dir $folder -no-color -out=plan.tmp
               terragrunt show --terragrunt-working-dir $folder -no-color plan.tmp >>${GITHUB_WORKSPACE}/plan.out
           done
           echo 'EOF' >> $GITHUB_ENV
         env:
           GOOGLE_CREDENTIALS: ${{ secrets.DBRE_GOOGLE_CREDENTIALS }}
           GOOGLE_ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}
```


Today for me to generate the template, I do the following:

```
      - name: Use template for a deleted file
        if: steps.changed-files-dir-names.outputs.any_deleted == 'true'
        run: |
          for folder in ${{ steps.changed-files-dir-names.outputs.deleted_files }}; do
            mkdir -p $folder
            if [[ $folder =~ "app" ]]; then
              cp .github/templates/user/app/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "iam" ]]; then
              cp .github/templates/user/iam/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "gcs" ]]; then
              cp .github/templates/gcs/terragrunt.hcl $folder/terragrunt.hcl
            elif [[ $folder =~ "cluster" ]]; then
              cp .github/templates/cluster/terragrunt.hcl $folder/terragrunt.hcl
              cp .github/templates/cluster/cluster.hcl $folder/../cluster.hcl
              count=`terragrunt show -json -no-color | jq '.values.outputs.DNS_REPLICA.value | length'`
              echo 'COUNT_DNS<<EOF' >> $GITHUB_ENV
              echo $count >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            fi
          done
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.DBRE_GOOGLE_CREDENTIALS }}
          GOOGLE_ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}
```

If I could put the deleted file in its path, just to run the action, it would solve my problem.

**Comment by jackton1** [comment]
@SamuelMolling This would be implemented next week as I have some other balls in the air at the moment.

**Comment by SamuelMolling** [comment]
Okay, this helps me a lot and I believe other people do too

**Comment by jackton1** [comment]
@SamuelMolling This is now available in the latest release:

- Set `recover_deleted_files` to `true` to restore deleted files to their previous locations
- Optionally set `recover_deleted_files_to_destination` to a directory where you want the deleted files stored.

**Comment by SamuelMolling** [comment]
Worked, thank you!!!

**Comment by SamuelMolling** [comment]
@jackton1 a doubt, today I have a file that needs to be recovered, but I wouldn't want it to enter as a modified file, you know?

My code is like this:

       - name: Run changed-files with dir_names
         id: changed-files-dir-names
         uses: tj-actions/changed-files@v36
         with:
           dir_names: "true"
           recover_deleted_files: "true"
           files: |
             terraform/mongodb-atlas/clusters/**/
           files_ignore: |
             **/cluster.hcl

I want to ignore cluster.hcl so it doesn't go into ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}, but I want it to be retrieved. It's possible?

**Comment by jackton1** [comment]
> Optionally set `recover_deleted_files_to_destination` to a directory where you want the deleted files stored.
