### ISSUE TITLE
[BUG] Error: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by onedr0p** [tj-actions/changed-files#1174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

```
  /usr/bin/git --version
  git version 2.40.1
  /usr/bin/git config --global core.quotepath on
  /usr/bin/git config --global diff.relative true
  /usr/bin/git rev-parse --is-shallow-repository
  true
  /usr/bin/git submodule status
  /usr/bin/git submodule status
  Error: Cannot read properties of undefined (reading 'replace')
```

### To Reproduce

https://github.com/onedr0p/home-ops/blob/d9d9d9fbc76ac4a1eceb8c07f722d924536d391f/.github/workflows/helmrelease-diff.yaml#L32-L41

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

It to work like in v35

### Relevant log output

```shell
https://github.com/onedr0p/home-ops/actions/runs/5085515752/jobs/9139056450
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
This should be resolved in latest release

**Comment by onedr0p** [comment]
Thanks, Nice work on the major refactoring!
