### ISSUE TITLE
Issue with dir_names, dir_names_max_depth, json, files

### ISSUE THREAD

**Issue by onedr0p** [tj-actions/changed-files#1186]
Version: v36.0.6

Error:

```
Error when evaluating 'strategy' for job 'publish-terraform'. .github/workflows/publish-terraform.yaml (Line: 55, Col: 15): Matrix vector 'project' does not contain any values
```

Workflow manifest: https://github.com/onedr0p/home-ops/blob/961ff6db1a3d93567011f2c6a1e99d1be32831ae/.github/workflows/publish-terraform.yaml#L30-L45

Workflow run: https://github.com/onedr0p/home-ops/actions/runs/5095027403

**Comment by jackton1** [comment]
@onedr0p I assume the error is because there aren't any changed directories.
![Screenshot 2023-05-26 at 4 53 18 PM](https://github.com/tj-actions/changed-files/assets/17484350/99e4e992-d743-43be-933c-f67122f3050c)

**Comment by onedr0p** [comment]
🤦 thanks for pointing that out you're absolutely correct. I jumped the gun a bit because of the major update.
