### ISSUE TITLE
[Feature] Support checking other repositories for changes

### ISSUE THREAD

**Issue by AlexCherrypi** [tj-actions/changed-files#1187]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I would like to check if (a file in) a different repo has changed or not.

I normally parse a file on every run of my action, but this is just wasting computing resources, if the file did not change. I could just load the parsing result from cache then.

This is why I would like to check if the file has changed since my last action run.

### Describe the solution you'd like?

an optional variable to specify the repository being checked for changes. Maybe in the format `username/reponame` ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@AlexCherrypi I believe this is already supported you’ll need to use the [checkout action](https://github.com/actions/checkout#checkout-multiple-repos-nested) and pass the path to the repository to this action you’ll also need to provide the `base_sha` and `sha` inputs.

For an example on how to use the changed-files action for a repository located in a different path search for “Get all changed files for a repository located in a different path” in the [Examples](https://github.com/tj-actions/changed-files#examples) section.

**Comment by AlexCherrypi** [comment]
@jackton1 Let me describe a more specific example for you to judge if this already supported, maybe even specifically by the Example you quoted

---

My action runs on a daily basis in the repository [AlexCherrypi/BNDnamegenerator/](https://github.com/AlexCherrypi/BNDnamegenerator/).

It then checks if in repository [hdaSprachtechnologie/odenet](https://github.com/hdaSprachtechnologie/odenet) the file [/odenet/wordnet/deWordNet.xml](https://github.com/hdaSprachtechnologie/odenet/blob/master/odenet/wordnet/deWordNet.xml) has changed since the last run of the action.

 `base_sha` and `sha` are available to check the file.

based on this output the rest of the action is configured...

---

Do you think, this is possible with the current version of this action?
