### ISSUE TITLE
[BUG] files input with directories not working as expected

### ISSUE THREAD

**Issue by florianbuth-sympower** [tj-actions/changed-files#1194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Up to v35 it was possible to specify directories to check for changed files without adding a glob pattern at the end. Now this seems to be required, but I am not sure if this is desired behaviour or accidental bug since README says it should be possible without glob pattern:
```yaml
files: docs/*.{js,html}  # Alternatively using: `docs/**` or `docs`
```

### To Reproduce

Using the following steps:
```yaml
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v36
        with:
          files: |
            .github/workflows

      - name: Set files changed flag
        if: steps.changes.outputs.any_changed == 'true'
        id: changeset
        run: echo "run_job=true" >> $GITHUB_OUTPUT
```

Make any changes in a workflow file. Second step gets skipped. Adding the glob pattern at the end (`.github/workflows/**`) makes it work again. Alternatively, change version to v35 and it also works again.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The changed files in a directory should be recognized again without explicitly adding the glob pattern at the end. Alternatively, the README could be clearer to bring out that this is required now.

### Relevant log output

```shell
Run tj-actions/changed-files@v36
  with:
    files: .github/workflows
  
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_from_source_file_separator: 
  
    files_separator: 
  
    files_ignore_separator: 
  
    files_ignore_from_source_file_separator: 
  
    path: .
    quotepath: true
    diff_relative: true
    dir_names: false
    dir_names_exclude_root: false
    json: false
    escape_json: true
    fetch_depth: 50
    since_last_remote_commit: false
    write_output_files: false
    output_dir: .github/outputs

...

##[debug]Node Action run completed with exit code 0
##[debug]Set output added_files = 
##[debug]Set output copied_files = 
##[debug]Set output modified_files = 
##[debug]Set output renamed_files = 
##[debug]Set output type_changed_files = 
##[debug]Set output unmerged_files = 
##[debug]Set output unknown_files = 
##[debug]Set output all_changed_and_modified_files = 
##[debug]Set output all_changed_files = 
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = .github/workflows/reusable.frontend.check-changes.yml
##[debug]Set output all_modified_files = 
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = .github/workflows/reusable.frontend.check-changes.yml
##[debug]Set output deleted_files = 
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Finishing: Get changed files for frontend
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@florianbuth-sympower This should be resolved now.

**Comment by florianbuth-sympower** [comment]
Indeed, now it is working again. Thank you so much for your quick action!
