### ISSUE TITLE
[BUG] After moving to `v36.0.10` action is not able to locatecommit

### ISSUE THREAD

**Issue by krukowskid** [tj-actions/changed-files#1204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

36.0.10 breaks the action for me. 
After update the action is unable to locate the commit sha

### To Reproduce

use below steps with tj-actions/changed-files set to `v36` or `v36.0.10`
```
      - name: Get repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get all changed files
        id: changed-other-files
        uses: tj-actions/changed-files@v36.0.10
        with:
          files_ignore: ${{ inputs.ignore_changed }}
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

action should resolve changed files

### Relevant log output

```shell
Warning: fatal: Invalid symmetric difference expression 9a6f6be724b80792a13e151181349242b6714efe...05707e12b7f957f4b00d92c3898d31a72a1cec9d
  
Warning: fatal: Invalid symmetric difference expression 9a6f6be724b80792a13e151181349242b6714efe...05707e12b7f957f4b00d92c[38]
 
Error: Unable to locate the commit sha: 9a6f6be724b80792a13e151181349242b6714efe
Error: Please verify that the commit sha is correct, and increase the 'fetch_depth' input if needed
Warning: fatal: Invalid revision range 9a6f6be724b80792a13e1511813492[42]
 
Error: Unable to determine a difference between 9a6f6be724b80792a13e151181349242b6714efe..05707e12b7f957f4b00d92c3898d31a72a1cec9d
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Can you create a public project with minimal code that replicates this issue ?

In the meantime, I'll close this for now pending your feedback.

**Comment by krukowskid** [comment]
@jackton1 I am unable to replicate this issue too... tested both v36.0.10 and v36.0.11. Reverted my workflow to use major version - v36. Maybe it was just temporary GitHub problem. Anyway thank you for super fast reaction!

**Comment by jackton1** [comment]
@krukowskid I was able to replicate this issue by force-pushing changes to an existing PR branch. It should be fixed now.
