### ISSUE TITLE
[Feature] Rename `files` -> `paths` [#tara-label-enhancement] [#tara-label-good first issue]

### ISSUE THREAD

**Issue by jackton1** [tj-actions/changed-files#125]
### Is your feature request related to a problem? Please describe.

Given that both files and directories can be added using the `files` input which seems limited to describing files.

### Describe the solution you'd like?

Proposed change here would be renaming `files` to `paths` which is more generic and can describe both file based paths and directories.

### Code of Conduct

*   I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Decided to go down the route of replicating the inputs for just directories.

**Comment by jackton1** [comment]
After much thought this seems like the best approach to prevent confusion with files and directories

**Comment by davorpa** [comment]
Is this a breaking change?

**Comment by jackton1** [comment]
Yes this would be a breaking change.

**Comment by jackton1** [comment]
Don't have much time to work on this closing for now.
