### ISSUE TITLE
[BUG] any_{changed,modified...} are always false when using dir_names

### ISSUE THREAD

**Issue by Spongman** [tj-actions/changed-files#1254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

https://github.com/Spongman/ts-rust-zig-deez/blob/master/.github/workflows/pr-worthy.yml

```   
      - name: Get changed files
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35.9.3
        with:
          since_last_remote_commit: true
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2
```

```
##[debug]Set output added_files = cpp-spongman
##[debug]Set output copied_files = 
##[debug]Set output modified_files = cpp-spongman
##[debug]Set output renamed_files = 
##[debug]Set output type_changed_files = 
##[debug]Set output unmerged_files = 
##[debug]Set output unknown_files = 
##[debug]Set output all_changed_and_modified_files = cpp-spongman
##[debug]Set output all_changed_files = cpp-spongman
##[debug]Set output any_changed = false
##[debug]Set output only_changed = false
##[debug]Set output other_changed_files = 
##[debug]Set output all_modified_files = cpp-spongman
##[debug]Set output any_modified = false
##[debug]Set output only_modified = false
##[debug]Set output other_modified_files = 
##[debug]Set output deleted_files = 
##[debug]Set output any_deleted = false
##[debug]Set output only_deleted = false
##[debug]Set output other_deleted_files = 
##[debug]Finishing: Get changed files```

NOTE: `any_changed` is `false` EVEN THOUGH files in `cpp-spongman` were changed.

### To Reproduce

(see workflow above)

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04, ubuntu-18.04

### Expected behavior?

(see workflow above)

### Relevant log output

```shell
(see workflow above)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@Spongman Based on the documentation `any_{changed,modified...}` are only set to true if you provide patterns using the `files` or `files_ignore` inputs.

**Comment by Spongman** [comment]
I read the documentation. It says:

INPUT | TYPE | REQUIRED | DEFAULT | DESCRIPTION
-- | -- | -- | -- | --
files | string | false |   | File and directory patterns todetect changes using only theselist of file(s) (Defaults to the entire repo) NOTE:Multiline file/directory patterns should notinclude quotes.


"**Defaults to the entire repo**"

**Comment by jackton1** [comment]
The concept of `any_(change,modified,deleted)` relies on the file patterns which is set to `true` when any of the patterns you provide are detected to have changes like it’s mentioned in the [outputs](https://github.com/tj-actions/changed-files#outputs) documentation.

```yml
      - name: Get changed files
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v36
        with:
          files: |
            .github/workflows
            tests
          since_last_remote_commit: true
          dir_names: true
          dir_names_exclude_root: true
          dir_names_max_depth: 2
```

If any files within either `.github/workflows` or the `tests` folder changes then `any_(change,modified,deleted)` would be set to `true` this does apply to changes in the entire repository.

I assume your use case would be to detect if any file changes in the entire repo without passing any patterns in which case that’s a feature request. Let me know if this helps
