### ISSUE TITLE
warning: <> multiple merge bases, using <>

### ISSUE THREAD

**Issue by cnpatric** [tj-actions/changed-files#1257]
Hi,

we discovered this and are not sure what is happening here, the action returned no changed files despite files being changed in the PR.

warning: daeace9...a0af184: multiple merge bases, using

Run tj-actions/changed-files@v35
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v17.2.5
/usr/bin/git rev-parse --show-toplevel
/usr/bin/git diff --diff-filter=D --name-only daeace9...a0af184
warning: daeace9...a0af184: multiple merge bases, using 6dfbd7e
Warning: warning daeace9...a0af184: multiple merge bases, using 6dfbd7e

Successfully created paths-output-file: /tmp/6c99a4.txt

I saw that this is connected to not having the latest changes from the destination branch but if there are no merge conflicts there isn't much of a need to merge latest changes from destination into origin right?

Any hints on how to proceed here?

**Comment by jackton1** [comment]
@cnpatric I’ll suggest upgrading to the latest version [v36](https://github.com/tj-actions/changed-files/releases/v36)
