### ISSUE TITLE
[BUG] Cannot recognize file pattern when using files_yaml

### ISSUE THREAD

**Issue by wkt-mineral** [tj-actions/changed-files#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When using `files_yaml` with file pattern like `**.js`, `Unresolved alias (the anchor must be set before the alias): *.sql` error appears.

### To Reproduce

      - name: Get changed files
        id: changed-files-yml
        uses: tj-actions/changed-files@v36
        with:
          files_yaml: |
            sql:
              - **.sql
            all:
              - **

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

sql should include all .sql changed files while all should have all changed files.

### Relevant log output

```shell
Run tj-actions/changed-files@v36
changed-files
Error: Unresolved alias (the anchor must be set before the alias): *.sql
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jpenna** [comment]
@wkt-mineral What is the solution?

**Comment by jackton1** [comment]
Hi @jpenna @wkt-mineral you’ll need to use quotes.

```yml
…
      files_yaml: |
        sql:
          - ‘**.sql’
        all:
          - ‘**’
```
