### ISSUE TITLE
Download the changed files option

### ISSUE THREAD

**Issue by ns-ggeorgiev** [tj-actions/changed-files#1294]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I am having file by file linters, that do not require cloning the whole repo to perform their work. If I can download all changed files based on github api, I assume for big repos that might be significantly faster for most commits.

### Describe the solution you'd like?

an option, that if true, downloads the files that have being changed/modified, preserving the file structure naming etc.

### Describe alternatives you've considered?

I am doing the same now with cloning the repo 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@ns-ggeorgiev This is already implemented and would be released momentarily
