### ISSUE TITLE
[Feature] Get specific changed files reading a file

### ISSUE THREAD

**Issue by Sonic0** [tj-actions/changed-files#130]
### Is your feature request related to a problem? Please describe.

Hi guys!
I have a Step with a lot of entries in `files:` input and those entries often change. Since I already have an existing file with all files that could change (one for line), is there the possibility to provide this specific file to read from?

### Describe the solution you'd like?

An example of implementation:

source file `files-list.txt`:
```
my-file.txt
test.txt
new.txt
test_directory
.(png|jpeg)$   
.(sql)$
^(mynewfile|custom)
```
Action step:
```bash
- name: Get specific changed files from a file
  id: changed-files-specific
  uses: tj-actions/changed-files@vX.x
  with:
    read-from-file: files-list.txt
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@Sonic0 This should be available in the latest release.

**Comment by Sonic0** [comment]
> @Sonic0 This should now be available in the latest [release](https://github.com/tj-actions/changed-files/releases/tag/v8.6).

Thanks a lot! :fireworks:
