### ISSUE TITLE
[Feature] Get Changed files since last successful Action run

### ISSUE THREAD

**Issue by patroza** [tj-actions/changed-files#131]
### Is your feature request related to a problem? Please describe.

Im trying to find changes not since the last commit on main branch, but since the last commit on main branch with a successful action run.

I found this handy action: https://github.com/nrwl/last-successful-commit-action
but I find no way to define which commit to compare to.
I did find the `sha` config variable, but apparently that is to say "what is the current" commit. Not what is the target commit to compare to.

### Describe the solution you'd like?

Perhaps a `target_sha` setting?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@patroza This should now be available in the latest [release](https://github.com/tj-actions/changed-files/releases/tag/v8.7)
