### ISSUE TITLE
[Feature] Allow skipping fetching history in shallow repositories

### ISSUE THREAD

**Issue by JavaScriptBach** [tj-actions/changed-files#1335]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

This action currently unconditionally fetches history on pull request events. This can take up to 1 minute.

### Describe the solution you'd like?

Provide an input that allows one to skip fetching history. In my use case, I'm choosing the SHAs myself and I've already fetched the history required.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@JavaScriptBach I believe you can specify the fetch depth using the `fetch_depth` input.

**Comment by JavaScriptBach** [comment]
@jackton1 Setting `fetch_depth: 0` does not allow me to escape this logic: https://github.com/tj-actions/changed-files/blob/aecc5ebeee84c2358e83fc9101ef1a70bd0581ac/src/commitSha.ts#L95

**Comment by pl4nty** [comment]
@jackton1 `fetch_depth: 2` still causes delays (~1 minute in my case), even though I'm using `actions/checkout` with `fetch-depth: 2`

**Comment by jackton1** [comment]
@pl4nty @JavaScriptBach This is now available in the latest release, setting `skip_initial_fetch` to `true` should skip fetching the initial history.

> Note: This could lead to weird errors so ba sure to fetch any history necessary to perform the diff.

**Comment by pl4nty** [comment]
@jackton1 thanks, this has cut my runtimes by 30%
