### ISSUE TITLE
[Feature] Add support for tj-actions in the merge group queue feature

### ISSUE THREAD

**Issue by kdpisda** [tj-actions/changed-files#1384]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Yes, my feature request is related to a problem. The tj-actions GitHub action does not work correctly with the merge group queue feature. This means I cannot use tj-actions to automate merging pull requests that are part of a merge group.

The problem with this is that it prevents me from merging pull requests promptly. This can lead to delays in the development process and cause problems with the codebase.

I request that the team add support for tj-actions in the merge group queue feature. This would allow me to use tj-actions to automate merging pull requests that are part of a merge group, improving my workflow and making my code reviews more efficient.

I appreciate your consideration.

### Describe the solution you'd like?

I want the GitHub team to add support for tj-actions in the merge group queue feature. This would allow me to use tj-actions to automate merging pull requests that are part of a merge group.

Specifically, I would like the GitHub team to make the following changes:

- Add a new configuration option to the tj-actions GitHub action that allows users to specify whether or not they want to use the merge group queue feature.
- Update the tj-actions GitHub action to handle pull requests from a merge group correctly.
These changes would be straightforward to implement and would provide a significant benefit to users who are using tj-actions to automate the merging of pull requests.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @kdpisda, you can now use [tj-actions/changed-files](https://github.com/tj-actions/changed-files) with the merge groups feature no changes are required on your part if you use the latest major version [v37](https://github.com/tj-actions/changed-files/releases/v37)
