### ISSUE TITLE
[Feature] Please state the difference between fetch-depth and fetch_depth

### ISSUE THREAD

**Issue by rick-kenna** [tj-actions/changed-files#1410]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

What is the difference between `fetch-depth` and `fetch_depth`?  `fetch-depth` is mentioned here: IMPORTANT: For push events when configuring [actions/checkout](https://github.com/actions/checkout#usage) the fetch-depth should be set to either fetch-depth: 0 OR fetch-depth: 2 depending on your use case; and is in the examples.  However when used, an unrecognized error is given and the you are informed to use `fetch_depth`.  `fetch_depth` is in the Input Table and is defaulted to 50.

So which one are you supposed to use?

### Describe the solution you'd like?

Either an explanation of the difference or just use one them.  If the `fetch-depth` is related to `--depth` in cloning, maybe a pointer to it would be helpful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @rick-kenna [Please see the answer in this Discussion](https://github.com/tj-actions/changed-files/discussions/1411), I'll also suggest starting a new discussion or responding to the discussion if you require further assistance in the future. 

Thanks
