### ISSUE TITLE
[BUG] <any_changed doesn't capture changes due to renaming files>

### ISSUE THREAD

**Issue by linnea-foreflight** [tj-actions/changed-files#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

I would expect any_changed to be true when there is a renamed file. It looks like any changed doesn't take renamed files into account.

### To Reproduce

Rename a file in the specified directory and then check the any_changed flag. 
<img width="610" alt="Screen Shot 2021-07-23 at 4 04 42 PM" src="https://user-images.githubusercontent.com/78982555/126835610-48ee8f62-3bca-4fa3-86ed-94ba223ee702.png">

For the specific case when I came across this, the file was renamed (moved from a directory outside the one specified into the specified AutomatedTests directory) but also had additional changes. It only showed up in the renamed files list.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

If there is anything listed for "All changed files" that the any_changed flag would be true.

### Relevant log output

```shell
Checking for file changes: "AutomatedTests"...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: 
  Renamed files: AutomatedTests/DownloadDatabaseTestCase.swift
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed files: AutomatedTests/DownloadDatabaseTestCase.swift
  All modified files: 
  Input files: AutomatedTests
  Matching modified files:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@linnea-foreflight This should be resolved in the latest release
