### ISSUE TITLE
[Feature] Support fetching modified files of a PR on the merge queue

### ISSUE THREAD

**Issue by Safrout1** [tj-actions/changed-files#1443]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I wanted to know the modified files of a PR, I can get that quite easily on the PR itself, but once the PR is in the merge queue and the queue is running the workflows, the action does not get the modified files right.

### Describe the solution you'd like?

If a repository is using a merge queue to merge PRs to it. Workflows / actions run can run on pull_request and on merge_group, the latter runs after the PR is in the merge queue, I would like to know the modified files there.

### Describe alternatives you've considered?

I have not found any other thing that would solve this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Safrout1** [comment]
I have not tested it, it is just that you do not say that you support it in the readme [here](https://github.com/marketplace/actions/changed-files). My usage is that I want to find if a PR has non-.md files, and if it doesn't I will skip all jobs of testing/etc. Those jobs run on the pull request and also on the merge queue. So, if you already support it, that will be great.

**Comment by jackton1** [comment]
Oh okay, It is included in the README, but it seems that might not be too obvious.

<img width="740" alt="Screenshot 2023-08-08 at 10 15 56 AM" src="https://github.com/tj-actions/changed-files/assets/17484350/81ab74d1-9587-4982-8083-ff757b38d1af">

### I've also added it to the example which would moved to a docs folder soon.

<img width="655" alt="Screenshot 2023-08-08 at 10 19 22 AM" src="https://github.com/tj-actions/changed-files/assets/17484350/cb3d33b4-f291-4135-ac34-0d83337f6903">
