### ISSUE TITLE
[Feature] Availability to check specific files changes

### ISSUE THREAD

**Issue by clauBv23** [tj-actions/changed-files#1447]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I started using `changed-files` a few days ago, I'm using the following configuration 
``` with:
          json: true
          quotepath: false
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
```
I only want to check the dir that changes, but there are some specific scenarios when I would like to know if there is a file in the current directory that changes (ex. if the .json changes ).  

I went over the documentation and didn't find a way to accomplish it.

### Describe the solution you'd like?

It would be really helpful if I could also get if some specific files changes.

 I was thinking of something like :

``` with:
          json: true
          quotepath: false
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
          include_files: [list of needed files paths]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @clauBv23 can you explain what you expect the outputs to be using a directory structure?

**Comment by clauBv23** [comment]
Hi @jackton1, sure. 
Currently, I'm only receiving the changed directories but I would also know if there are some files that changed, for example
In the following project structure: 
```
- Root
   - .github
      - workflows
         - wf.yaml  
   - src
      - Pkg1
         - file1
         - file2
      - Pkg2
         - file21
         - file22
   - pkg.json
```
it will show the changes in files inside `pkg1` `pkg2` and `workflow` but not the changes in `pkg.json`. 
 The current output will be something like 
```
[".github/workflows", "src/pkg1", "src/pkg2"]
```
and the expected one
```
[".github/workflows", "src/pkg1", "src/pkg2", "pkg.json"]
```

**Comment by jackton1** [comment]
Hi, @clauBv23 this should be available in the latest [v38 release](https://github.com/tj-actions/changed-files/releases/tag/v38).

**Comment by clauBv23** [comment]
Thanks @jackton1, I'll take a look at it

**Comment by jackton1** [comment]
Hi @clauBv23 you can now provide the patterns using [dir_names_include_files](https://github.com/tj-actions/changed-files#input_dir_names_include_files) input.
