### ISSUE TITLE
[BUG] Getting Invalid symmetric difference expression for git submodule changes

### ISSUE THREAD

**Issue by soumyamahunt** [tj-actions/changed-files#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When comparing git submodule changes,  I am getting following warning:
>   Warning: fatal: Invalid symmetric difference expression 828e49bccdcfec756205a7600275de1111604b16...f46a0f650b308f59f3ff6caf988677a23671059b<br/>
Warning: Please ensure that submodules are initialized and up to date. See: https://github.com/actions/checkout#usage

The workflow file can be found here: https://github.com/SwiftyLab/swift-version/blob/318a057b190fb3d34401676cda8612de3e3c5bc0/.github/workflows/main.yml#L192, I have enabled submodules option in checkout action but still getting the same error.

### To Reproduce

1. Add git submodule to a repo.
2. Update submodule and run this action.
3. See the error.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Action should succeed in checking git submodule changes.

### Relevant log output

```shell
Step log can be found here: https://github.com/SwiftyLab/swift-version/actions/runs/5942690901/job/16116190900#step:4:1.

Also attached log archive.
```

### Anything else?

[logs_678.zip](https://github.com/tj-actions/changed-files/files/12412074/logs_678.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @soumyamahunt this should be resolved in the latest [v38 release](https://github.com/tj-actions/changed-files/releases/tag/v38).

**Comment by soumyamahunt** [comment]
@jackton1 while I am not seeing this error now, I am seeing a different error:
>   diff --git a/swiftorg b/swiftorg
  index 828e49b..04c92b1 160000
  --- a/swiftorg
  +++ b/swiftorg
  @@ -1 +1 @@
  -Subproject commit 828e49bccdcfec756205a7600275de1111604b16
  +Subproject commit 04c92b17129fd21d1cc04da3d4f765c56546d8bb
  /usr/bin/git merge-base 828e49bccdcfec756205a7600275de1111604b16 04c92b17129fd21d1cc04da3d4f765c56546d8bb
  fatal: Not a valid commit name 828e49bccdcfec756205a7600275de1111604b16
  Warning: Unable to find merge base between 828e49bccdcfec756205a7600275de1111604b16 and 04c92b17129fd21d1cc04da3d4f765c56546d8bb
  /usr/bin/git diff --name-status --ignore-submodules=all --diff-filter=ACDMRTUX 828e49bccdcfec756205a7600275de1111604b16..04c92b17129fd21d1cc04da3d4f765c56546d8bb
  fatal: Invalid revision range 828e49bccdcfec756205a7600275de1111604b16..04c92b17129fd21d1cc04da3d4f765c56546d8bb
  Warning: fatal: Invalid revision range 828e49bccdcfec756205a7600275de1111604b16..04c92b17129fd21d1cc04da3d4f765c56546d8bb<br/>
Warning: Please ensure that submodules are initialized and up to date. See: https://github.com/actions/checkout#usage

Workflow log available [here](https://github.com/SwiftyLab/swift-version/actions/runs/5951738439/job/16142157012?pr=52#step:4:885). Is this related? Should I create a new issue?

**Comment by jackton1** [comment]
Yes, you can create a new issue @soumyamahunt

**Comment by jackton1** [comment]
Hi @soumyamahunt, you’ll need to enable the `fetch_additional_submodule_history` input to resolve the error
