### ISSUE TITLE
[Feature] any_changed doesn't capture changes due to deleting files

### ISSUE THREAD

**Issue by linnea-foreflight** [tj-actions/changed-files#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

 I would expect any_changed to be true when there is a deleted file. It looks like any changed doesn't take deleted files into account.

### To Reproduce

Delete a file in the specified directory and then check the any_changed flag.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

If there is anything listed for "All changed files" that the any_changed flag would be true.

### Relevant log output

```shell
Checking for file changes: "automated-testing-gaps.md"...  
  Checking for file changes: "AutomatedTests"...
  Added files: 
  Copied files: 
  Deleted files: AutomatedTests/SettingsMonitorTests.swift
  Modified files: 
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed files: ffm/AutomatedTests/SettingsMonitorTests.swift
  All modified files: 
  Input files: automated-testing-gaps.md AutomatedTests
  Matching modified files: 
  Non Matching modified files: UserPreferences.m AppDelegate.m
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@linnea-foreflight This should be resolved in the latest release. Thanks

**Comment by linnea-foreflight** [comment]
Thanks!

**Comment by jackton1** [comment]
@linnea-foreflight Just a heads up decided to stick with the previous design in the latest release. 

Even though a deleted file can be considered as modified but the general use case would be for files that are changed or renamed and still available in version control, like you mentioned as opposed to deleted files.

You can use `outputs.deleted_files` to get around the issue in the meantime.
