### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SadriG91** [tj-actions/changed-files#15]
Is it possible to add support for push commits?
i think it would be even more useful

**Comment by jackton1** [comment]
Would this be push to the same branch ?

**Comment by SadriG91** [comment]
Yes!

**Comment by jackton1** [comment]
@SadriG91 Sorry for the delay but this should be available in [v4](https://github.com/tj-actions/changed-files/releases/tag/v4)

**Comment by SadriG91** [comment]
@jackton1 Thanks for the update!
