### ISSUE TITLE
[Feature] Error handling for case where manually entered base_sha is missing

### ISSUE THREAD

**Issue by Weetbix** [tj-actions/changed-files#1509]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Currently I have a scenario where I am setting the `base_sha` manually, and the action detects that the sha is missing but there is no way for me to handle the error, and the output of the file changes looks like "none".

The output looks like:
```
Using local .git directory
  Running on a pull_request (synchronize) event...
  Repository is shallow, fetching more history...
  Completed fetching more history.
  Error: Unable to locate the commit sha: 744217a70ef95b[49](https://github.com/blah/blah/698ab38fbb34a9ebb847cfb5
  Error: Please verify that the commit sha is correct, and increase the 'fetch_depth' input if needed
  Retrieving changes between 744217a70ef95b49698ab38fbb34a9ebb847cfb5 (main) → 4f3c[54](https://github.com/blah/blah/actions/runs/6021787942/job/16335270197?pr=970#step:5:55)aea0a96eeaa4cdca67f78bb360fad04144 (jh/improve-skip-flow-2)
  Warning: fatal: Invalid symmetric difference expression 744217a70ef95b49698ab38fbb34a9ebb847cfb5...4f3c54aea0a96eeaa4cdca67f78bb360fad04144
```

For example I have a workflow where I want to check against the last successful workflow commit on the branch:

- Commit A pushed to branch
- Commit A gets green tick ✅ 
- Commit B pushed to branch, action checks diff between A -> B ✅
- Rebase and force push, now branch only contains Commit C, but last successful check is Commit B
- Action reports it cant find Commit B, but no way to handle this error.

### Describe the solution you'd like?

An output I can check to see if this error is occuring, or a flag I can set to make this step fail

### Describe alternatives you've considered?

I will manually check first if Commit B still exists in the new branch, but it will be duplicated effort

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @Weetbix this is now supported in the latest release you can set the `fail_on_initial_diff_error` input to `true` which would fail the step.
