### ISSUE TITLE
[BUG] Dedupe the output list of changed files

### ISSUE THREAD

**Issue by jackton1** [tj-actions/changed-files#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

There's a possibility of returning the same file twice when it matches one or more regex used in the files input.

### To Reproduce

1. Create a `.github/workflows/test.yml`
2. Enter the following
```
  uses: tj-actions/changed-files@v9
  with:
    files: |
		path-to-files
	    .(js|ts|tsx|scss)$
  ...
```

### What OS are you seeing the problem on?

all

### Expected behavior?

The list of changed files returned shouldn't be duplicated.

### Relevant log output

```shell
All changed files: path-to-files/test.js path-to-files/test.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mabdullah99** [comment]
@jackton1 I still get duplicate outputs in `all_changed_and_modified_files` when using both `files` and `dir_names` inputs

**Comment by jackton1** [comment]
@mabdullah99 can you provide the related logs where you saw duplicates ?
