### ISSUE TITLE
[BUG] Changed files after pull request merge not working

### ISSUE THREAD

**Issue by remisalmon** [tj-actions/changed-files#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running the action after a pull request merge to get the list of files changed in the source branch no files are found because the action is comparing the source branch to the merge commit in the target branch.

This is sort of expected since the diff between the target branch and the source branch is null after merging the source branch but according to https://github.com/tj-actions/changed-files/issues/874 showing the list of files changed should be possible.

### To Reproduce

1. Setup the action to run when `github.event.pull_request.merged == true`
2. Print `all_modified_files` shows an empty string

Reproduced in https://github.com/remisalmon/test-actions/actions/runs/6124183707/job/16623667321 with this workflow: https://github.com/remisalmon/test-actions/blob/main/.github/workflows/ci.yml and this pull request: https://github.com/remisalmon/test-actions/pull/1.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

The action should still show the list of changed files between the target branch and source branch after the source branch is merged in the target branch.

### Relevant log output

```shell
See https://github.com/remisalmon/test-actions/actions/runs/6124183707/job/16623667321
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @remisalmon, this should be fixed in the latest release
