### ISSUE TITLE
Setting remote URL breaks other steps that are using it

### ISSUE THREAD

**Issue by grzegorzkrukowski** [tj-actions/changed-files#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

It seems that:
`git remote set-url origin "https://${INPUT_TOKEN}@github.com/${GITHUB_REPOSITORY}"`
is permanently breaking the next steps we have in the workflow that depends on it.

After executing the script origin should be set to it's original value instead of keeping it with `INPUT_TOKEN`

### To Reproduce

1. Add `changed-file` step
2. Check in next step that origin is permanently modified which may break other scripts.

### What OS are you seeing the problem on?

all

### Expected behavior?

I would expect to not have modified origin at the end of script execution

### Relevant log output

Our other scripts depend on `git origin` string comparison for security reasons, having token forced is making them fail.

### Anything else?

I work around that issue by adding extra step that is resetting changes:
```
- name: Fix get changed files origin
        run: |
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@grzegorzkrukowski The fix should be available in the latest release. Thanks
