### ISSUE TITLE
[BUG] Error: xargs: unmatched single quote

### ISSUE THREAD

**Issue by fernandobrito** [tj-actions/changed-files#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

I get the following error sometimes:

```
xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
```

### To Reproduce

I haven't had time to try to reproduce it locally. I'm first posting here to check if this is a known issue or if someone else already had it before I spend more time troubleshooting it (I'm a `bash` novice).

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

There should be no errors.

### Relevant log output

```shell
Run tj-actions/changed-files@2f8c46f9d79d979656108f4fc4414c378ee4abed
  with:
    files: ^transform/snowflake-dbt/.*
  
    base_sha: 01f529cacb2dff32b9a54cf946dce1c74c039a5a
    sha: c6e8af0e7208d28653aab87352c9d5f81cc7742b
    token: ***
    separator:  
  env:
    SNOWSQL_ACCOUNT: ***
    SNOWSQL_USER: ***
    SNOWSQL_PWD: ***
    SNOWSQL_WAREHOUSE: dbt_ci_wh
changed-files
  Getting HEAD info...
  From https://github.com/voiapp/data-pipelines
   * [new branch]        master     -> master
   * [new branch]        master     -> origin/master
  Retrieving changes between 01f529cacb2dff32b9a54cf946dce1c74c039a5a (master) → c6e8af0e7208d28653aab87352c9d5f81cc7742b (backfill_MRS_vehicle_not_available)
  Checking for file changes: "^transform/snowflake-dbt/.*"...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: transform/snowflake-dbt/models/analytics/magic_ride_session.sql transform/snowflake-dbt/models/model/engineering/user_experience/start_ride_attempt.sql
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed files: transform/snowflake-dbt/models/analytics/magic_ride_session.sql transform/snowflake-dbt/models/model/engineering/user_experience/start_ride_attempt.sql
  All modified files: transform/snowflake-dbt/models/analytics/magic_ride_session.sql transform/snowflake-dbt/models/model/engineering/user_experience/start_ride_attempt.sql
  xargs: unmatched single quote; by default quotes are special to xargs unless you use the -0 option
  Error: Process completed with exit code 1.
```

### Anything else?

Great project, thanks for maintaining it! Very useful.

For security reasons, I have to hardcode the commit SHAs of external GitHub Actions. The one I'm using for this report is https://github.com/tj-actions/changed-files/commit/2f8c46f9d79d979656108f4fc4414c378ee4abed, which is the equivalent of v9.3. 

Screenshot of the error: ![image](https://user-images.githubusercontent.com/196840/131144303-a8fdc7e9-d09f-4e62-b620-dff034996311.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fernandobrito** [comment]
Hi @jackton1, thanks a lot for the quick action, really appreciated! I will give the newly released version a try next week.

I have an automation that makes a "backup" of some configuration files from external systems into my repository and it uses the original names from the source systems to create folders and files. Now I realize that this automation indeed created files and folders with quotes on the names:

![image](https://user-images.githubusercontent.com/196840/131219385-9afd800c-1277-41c8-a108-99d3c94cb244.png)

**Comment by jackton1** [comment]
@fernandobrito Okay that makes sense, glad you found the root cause let me know if the error still persist. 

Thanks
