### ISSUE TITLE
Main should fail if node version > 16 and release notes need updating.

### ISSUE THREAD

**Issue by jayunit100** [tj-actions/changed-files#1752]
Sounds like versions after 38 require a new node.js ..... ( as we can see when looking at the .github/ test spec changes for version 39....)

I think probably we should:

- add breaking change notes to the v39.0 so folks running can track and pin versions as needed...who are running node on node 16...

- Update readme w node version reqs.

- Update main to fail on node version being incorrect ?

**Comment by jackton1** [comment]
This issue doesn’t use the provided issue templates and would be closed as a result.
