### ISSUE TITLE
[Feature] Documentation for difference between all_changed_files and all_modified_files

### ISSUE THREAD

**Issue by iacobfred** [tj-actions/changed-files#177]
### Is your feature request related to a problem? Please describe.

I can't tell the difference between `all_changed_files` and `all_modified_files`.

### Describe the solution you'd like?

I would love it if the two were clearly distinguished in the documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Have you taking a look at https://github.com/tj-actions/changed-files#outputs. I know the `all_changed_files` output might need a better description
