### ISSUE TITLE
[Feature] Check if changed files have added strings or removed strings

### ISSUE THREAD

**Issue by jimmysafe** [tj-actions/changed-files#1791]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hi! Is there a way to check if in the changed file have only been removed stuff and not added new content?

Example:
I have a changed file that gets detected and it only includes removed strings like so:

![Screenshot 2023-12-13 at 12 17 13](https://github.com/tj-actions/changed-files/assets/12184812/e5bacffa-2e02-42d0-9a06-2f295a884293)

Thanks in advance

### Describe the solution you'd like?

I would like the changed-files response to return something like `removedOnly: true` in this case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @jimmysafe, unfortunately this action doesn’t this features. Any content change detection would be up to you to handle in a script or a third party solution.
