### ISSUE TITLE
[Feature] Specify sed delimiter or escaping forward slashes used in separator

### ISSUE THREAD

**Issue by adamsilkcm** [tj-actions/changed-files#180]
### Is your feature request related to a problem? Please describe.

When using a separator containing a forward slash, sed interprets it as a delimiter, leading to errors such as 
```
Checking for file changes: ...
sed: -e expression #1, char 9: unknown option to `s'
```
https://github.com/tj-actions/changed-files/blob/main/entrypoint.sh#L118-L136

### Describe the solution you'd like?

Either an option to choose the delimiter with a default to `/`, e.g. setting SED_DELIMITER=@ would turn the sed commands into `sed 's@  *@'"$INPUT_SEPARATOR"'@g'` and / would not be interpreted as a delimiter.
or
Escaping forward slashes used in separator.

The latter may reduce the number of initial errors or confusion more than the former.

### Describe alternatives you've considered?

Escaping forward slashes works fine for short separators, e.g. `\/` but becomes onerous when using unixy paths, web addresses, etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@adamsilkcm This should be resolved in the latest release. Thanks
