### ISSUE TITLE
[Feature] add support for changed files off workflow_run trigger

### ISSUE THREAD

**Issue by ann8ty** [tj-actions/changed-files#1826]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

sandbox (on push tags)
  Retrieving changes between 
1b1bd7ff69b377f5bee8d61b0535bdc177f19ee1 (v4.0.49) → last tag
da253ebfa66678e32a8e5f5715708494b8f35cec (v4.0.50) commit
(works, sees the file diffs)

workflow run trigger

test (on workflow_run workflows [sandbox] types: completed)
  Retrieving changes between 
fd3336c325eadcf35321d32ef101bb75b23932af (main) →  (sha matches parent)
da253ebfa66678e32a8e5f5715708494b8f35cec (main) / (sha matches v4.0.50)
(does not work because the parent is not the last tag, so there are no file diffs)

### Describe the solution you'd like?

i would like the same file diffs to run after workflow_run as on push tags

i have github.event.workflow_run.head_branch = v4.0.50
and head_sha

### Describe alternatives you've considered?

      - name: Get requirements changed files
        uses: tj-actions/changed-files@v41
        id: changed-requirements-file
        with:
          base_sha: ${{ github.event.workflow_run.head_sha }}
          files: |
            requirements.txt

### Anything else?

example of first workflow (works as described in documentation)
[example_sandbox_on_tags.txt](https://github.com/tj-actions/changed-files/files/13844896/example_sandbox_on_tags.txt)

example of triggered workflow from workflow run (does not work / feature request) 
[example-triggered-workflow-run.txt](https://github.com/tj-actions/changed-files/files/13844892/example-triggered-workflow-run.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi, @ann8ty this is already supported that said if you notice any issues you can create another issue and include any relevant logs.

Example Open source projects using the workflow_run event
- https://github.com/berkaymizrak/Resume-Django-Web-App/blob/41f7eeece623bb7f760fd48959dcdb9c6d9f6d46/.github/workflows/upload-static.yml
- https://github.com/GSA/notifications-admin/blob/9a3dbb954df6dfa5742dfcf4c519a244a94ec7e8/.github/workflows/deploy.yml

**Comment by ann8ty** [comment]
@jackton1 thanks for the quick response, both cases you sent use branches, not tags.  it is not working with tags even with the specified sha, as in my example.

**Comment by jackton1** [comment]
Hi @ann8ty some details are missing that are required to provide a solution.

1.  A Workflow code snippet which includes both the checkout and changed-files actions
2.  A full log output with debugging enabled which includes sections of the `tj-actions/changed-files` debug logs.

**Comment by jackton1** [comment]
Here's a working example for this https://github.com/tj-actions/demo3/blob/main/.github/workflows/workflow-run.yml
