### ISSUE TITLE
[Feature] allow forcing the action to use Github API, even if local .git directory is present

### ISSUE THREAD

**Issue by gstokkink** [tj-actions/changed-files#1841]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

 I only want to do a shallow clone of the git repository (we use a monorepo, so full fetch is slow) in an initial step, and check the changed files using this action in a later step, using the Github API. However, the action checks if there is a .git directory present and then automatically performs a full fetch of the git repository, negating the performance benefit of the shallow clone.

### Describe the solution you'd like?

An input that forces this action to use the Github API, even if a .git directory is present.

### Describe alternatives you've considered?

Changing the order of the steps, i.e., first check the changed files using this action, and in a subsequent step perform the shallow clone. This is awkward and error-prone, however.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @gstokkink. have you considered running the action a separate job after which you can utilize the output?

**Comment by gstokkink** [comment]
That would slow things down and result in an explosion of jobs in my case, since I have to rely on `matrix`.

**Comment by jackton1** [comment]
Hi, @gstokkink can you clarify what you mean by "since I have to rely on matrix.".

Here's a working example of what I mean by using multiple jobs: https://github.com/tj-actions/demo3/blob/main/.github/workflows/multi-job.yml

**Comment by gstokkink** [comment]
@jackton1 neither link works for me

**Comment by jackton1** [comment]
Hi @gstokkink ive updated the link let me know if that works for you.

**Comment by jackton1** [comment]
Hi, @gstokkink this is now available in the latest release via the `use_rest_api` input.

**Comment by gstokkink** [comment]
@jackton1 excellent, thanks! 🙏

**Comment by gstokkink** [comment]
@jackton1 looks like the warning for incompatible inputs is not working 100% correctly. I receive the following warnings when using the new `use_rest_api` input:

```
  Warning: Input "path" is not supported when using GitHub's REST API to get changed files
  Warning: Input "quotePath" is not supported when using GitHub's REST API to get changed files
  Warning: Input "diffRelative" is not supported when using GitHub's REST API to get changed files
  Warning: Input "recoverFilesSeparator" is not supported when using GitHub's REST API to get changed files
  Warning: Input "recoverFilesIgnoreSeparator" is not supported when using GitHub's REST API to get changed files
  Warning: Input "oldNewSeparator" is not supported when using GitHub's REST API to get changed files
  Warning: Input "oldNewFilesSeparator" is not supported when using GitHub's REST API to get changed files
```

However, I have not (explicitly) set any of these inputs. Maybe it's because these inputs default to a non-empty string, and https://github.com/tj-actions/changed-files/blob/main/src/main.ts#L282 therefore evaluates to a truthy value?

**Comment by jackton1** [comment]
HI @gstokkink this should be resolved in the latest patch

**Comment by gstokkink** [comment]
@jackton1 thanks for the quick fix! 👍🏻 Good job on this action by the way, seems to work flawlessly. Only too bad the `path` argument does not work for the Github REST API approach, I'll see if I can whip up a PR for that. Useful for monorepos containing (and building) multiple services.

**Comment by jackton1** [comment]
Thanks, Unfortunately using `path ` input in the context of a REST API call isn’t supported due to the fact that no local file is used. But I’m open to reviewing a proposed change
