### ISSUE TITLE
[Feature] add option to ignore submodules

### ISSUE THREAD

**Issue by rantoniuk** [tj-actions/changed-files#2045]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

It's great that the submodules are supported, but I would actually like to ignore submodules during the scans. This is because the changes for submodules should be normally managed in their own workflows, not in the target repository that is consuming them.

Currently I see in the logs:
```
Set 'fetch_additional_submodule_history: true' to fetch additional submodule history for: subm
```

### Describe the solution you'd like?

I'd like to disable changed files detection in the paths defined by `.gitmodules`, e.g. `ignore_submodules: true/false`.

### Describe alternatives you've considered?

I'm ignoring the submodule directory now via 
```
files_ignore: |
  subA
  subB
```

but that doesn't improve the performance and it still shows the warning above. Also I need to maintain that list separately while it could be auto-populated from `.gitmodules` or from `git submodule | awk '{print $2;}'`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @rantoniuk you can now disable submodule diffs by setting the `exclude_submodules` to `true`
