### ISSUE TITLE
[BUG] Changes since Last commit on the branch brings all files since the beggining of the branch

### ISSUE THREAD

**Issue by iamtheef** [tj-actions/changed-files#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I am using the tool as documented but I still get all the files that were changed since the branch started

### To Reproduce

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        with:
          since_last_remote_commit: "true"
      
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Only the files since the last commit in the branch

### Relevant log output

```shell
src/caf/Dockerfile.api was changed
src/caf/Dockerfile.cron was changed
src/hqm/Dockerfile.api was changed
src/hqm/Dockerfile.cron was changed
src/ins/Dockerfile.api was changed
src/ins/Dockerfile.cron was changed
tracetag.sh was changed
.DS_Store was changed
.github/workflows/main.yaml was changed # ONLY THIS WAS CHANGED SINCE LAST COMMIT IN THE BRANCH
.github/workflows/release.yaml was changed
manage.py was changed
src/.DS_Store was changed
src/shared/core/minio.py was changed
src/aco/Dockerfile.api was changed
src/aco/Dockerfile.cron was changed
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iamtheef** [comment]
Hey, sure!
Let me know when this is patched ;) Glad to use your code

**Comment by jackton1** [comment]
Hi, @iamtheef there are several missing details required to provide feedback or replicate the issue.

1. Can you provide the entire log output with debug enabled, which includes details of what commit hash was compared
2. List the relevant commits you have in the PR/Branch where the action is triggered
3. Can you also provide more details of the workflow file including the event and checkout action configuration.

**Comment by jackton1** [comment]
A short example of this is the [following logs](https://github.com/tj-actions/changed-files/actions/runs/8762449100/job/24050227202?pr=2060#step:4:54)

<img width="983" alt="Screenshot 2024-04-26 at 3 17 36 PM" src="https://github.com/tj-actions/changed-files/assets/17484350/bddc8afc-84bd-4aae-b840-e54e1271c74b">

Commits compared
```
9f8502e58178464eefa82a2374eafdb01e016029 (feat/reduce-the-default-fetch-depth) → 22e061a3a53470796bc50dbe1fa9fb6b9973dd27 (feat/reduce-the-default-fetch-depth)
```

Commits of the branch
<img width="1347" alt="Screenshot 2024-04-26 at 3 19 59 PM" src="https://github.com/tj-actions/changed-files/assets/17484350/d0c0b98a-a0b9-4bf2-97c5-d630c34f2771">
