### ISSUE TITLE
[Feature] Get version of files before they were edited

### ISSUE THREAD

**Issue by justanotheranonymoususer** [tj-actions/changed-files#2089]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I need a CI that makes sure a change is correct, so if a file was edited, i need the old ver. There is already `recover_deleted_files`, but I need something like `recover_modified_files`. The feature is the same, just need not limit it to deleted.

### Describe the solution you'd like?

`recover_modified_files`?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @justanotheranonymoususer this seems like one off use case for now I’ll suggest utilizing a script that you can use to recover modified files. 

We can revisit this in the future if it does become a general problem.

**Comment by justanotheranonymoususer** [comment]
Isn't `recover_deleted_files` also a one-off problem then?
Basically I don't agree, I think it has many use cases, and it's a bummer to write a non-trivial script (with fetch and whatnot) for something you guys already worked on to implement correctly, all's needed is to not limit it to deleted files.

**Comment by justanotheranonymoususer** [comment]
Basically all that's needed is to control this:
https://github.com/tj-actions/changed-files/blob/35d5a4d79f865a1a8db02b9f6fb4c5cd4b4809ef/src/main.ts#L159
To be able to also pass 'M'
