### ISSUE TITLE
[BUG] Re-running a workflow triggered by a tag event causes the wrong previous tag to be selected

### ISSUE THREAD

**Issue by ptab** [tj-actions/changed-files#2106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have a workflow running on every tag push event that checks out the repository and lists files changed since the previous tag. This works perfectly for every new tag created, but if I choose to _Re-run all jobs_ after new tags have been created, this action gets confused and seems to select the tag before HEAD rather than the one before the tag the event relates to.

### To Reproduce

I created a repository showcasing this behaviour: 
* https://github.com/ptab/reproduce-changed-files-bug

All tags were created using:
```
git tag vN <sha> && git push --tags
```
without any modification to the workflow in between.

On [the logs of the workflow run for `v2`](https://github.com/ptab/reproduce-changed-files-bug/actions/runs/9214393061/attempts/1) you can see the output:
```
▸ Run tj-actions/changed-files@v44
▾ changed-files
  Using local .git directory
  Running on a push event...
  Retrieving changes between 5fa889e211f60f32d67ebc736fa8c4d9349eee75 (v1) → a941b77e83c28cf99e0fdacbc4c9cff4c17f9034 (v2)
  All Done!
```

After new tags were created, I selected _Re-run all jobs_ and I [got the following different output](https://github.com/ptab/reproduce-changed-files-bug/actions/runs/9214393061/attempts/2):
```
▸ Run tj-actions/changed-files@v44
▾ changed-files
  Using local .git directory
  Running on a push event...
  Retrieving changes between 2c6e163d9e9b97c388152308ff4c2c98283c5110 (v3) → a941b77e83c28cf99e0fdacbc4c9cff4c17f9034 (v2)
  All Done!
```
(The previous tag is now one in the future)

Nothing else changed between runs, other than new tags being pushed.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-22.04

### Expected behavior?

Re-running a workflow should select the same previous tag.

### Relevant log output

```shell
/usr/bin/git rev-parse --is-inside-work-tree
  true
  ##[debug]Has git directory: true
  ##[debug]Input file patterns: 
  ##[debug]
  ##[debug]File patterns: 
  ##[debug]Yaml file patterns: {}
  Using local .git directory
  /usr/bin/git --version
  git version 2.45.1
  /usr/bin/git config --global core.quotepath on
  /usr/bin/git config --global diff.relative true
  /usr/bin/git rev-parse --is-shallow-repository
  false
  /usr/bin/git submodule status
  Running on a push event...
  ##[debug]Getting current SHA...
  /usr/bin/git rev-parse HEAD
  a941b77e83c28cf99e0fdacbc4c9cff4c17f9034
  /usr/bin/git rev-parse --verify a941b77e83c28cf99e0fdacbc4c9cff4c17f9034^{commit}
  a941b77e83c28cf99e0fdacbc4c9cff4c17f9034
  ##[debug]Current SHA: a941b77e83c28cf99e0fdacbc4c9cff4c17f9034
  /usr/bin/git rev-parse --abbrev-ref HEAD
  HEAD
  ##[debug]Getting previous SHA...
  ##[debug]Getting previous SHA for tag...
  /usr/bin/git tag --sort=-creatordate
  v4
  v3
  v2
  v1
  /usr/bin/git rev-parse v3
  2c6e163d9e9b97c388152308ff4c2c98283c5110
  /usr/bin/git rev-parse --verify 2c6e163d9e9b97c388152308ff4c2c98283c5110^{commit}
  2c6e163d9e9b97c388152308ff4c2c98283c5110
  ##[debug]Previous SHA: 2c6e163d9e9b97c388152308ff4c2c98283c5110
  ##[debug]Target branch: v3
  ##[debug]Current branch: v2
  Retrieving changes between 2c6e163d9e9b97c388152308ff4c2c98283c5110 (v3) → a941b77e83c28cf99e0fdacbc4c9cff4c17f9034 (v2)
```

### Has all relevant logs been included?

- [X] I've included all relevant logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @ptab this should be resolved in the latest release.

**Comment by ptab** [comment]
I can confirm that this release solves the issue, thanks for the quick fix @jackton1!
