### ISSUE TITLE
[Feature] Ignore files with only comment changes

### ISSUE THREAD

**Issue by willryan-stemcell** [tj-actions/changed-files#2133]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

My devs would like to be able to exclude files if only comments have been changed so that PHPUnit doesn't trigger when only comments are added to PHP files.

### Describe the solution you'd like?

- Check lines in modified files
- If modified lines are only comments ignore the file
-

### Describe alternatives you've considered?

Writing a custom script to handle this after I get a list of modified files from `changed-files`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
HI @willryan-stemcell, 

Unfortunately, this request is out of scope for the changed files action, as it does not read the contents of the files. To support your use case, I would suggest writing a custom script to determine if the changes in all modified files are strictly comments.
