### ISSUE TITLE
[Feature] Add support for previous_sha and current_sha outputs

### ISSUE THREAD

**Issue by gm42** [tj-actions/changed-files#2371]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Not related to a problem. I have seen that the action text output tells about which SHAs were used for the comparison:
```
Retrieving changes between b21edcea84825a0829e057c58fe245e6ca5a00df (main) → 92fbd4595dcaf9a1e2e92723247ce4f38a926817 (feat/my-branch)
```

This corresponds to this line of code: https://github.com/tj-actions/changed-files/blob/05f0aba931687dcad284e6c7f2e049c258a53fb8/src/main.ts#L131C46-L131C57

### Describe the solution you'd like?

It would be great if I could extract these values via `outputs`, to re-use them in other steps.

### Describe alternatives you've considered?

One can use `${{ github.event.pull_request.base.sha }}` and `${{ github.event.pull_request.head.sha }}` instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @gm42 , can you provide some more details about your use case?

**Comment by gm42** [comment]
@jackton1 sure: one example is that after running this action one might want to put the used hashes in a text report telling about which files changed, or call `git diff`. I think it is necessary for composition with other actions which need a commit hash, in case one wants to also refer to the `main` branch commits.

**Comment by jackton1** [comment]
Hi @gm4, okay I’d suggest taking a look at https://github.com/nrwl/nx-set-shaswhich covers your use case. Since this action primary focus is to retrieve changed files.

**Comment by gm42** [comment]
Thanks for your answer; I disagree, that action is overkill for this and does not serve the purpose: this action is already deciding which commit SHAs to use, so by using a different action they could be different.

I will use a fork, no problem.
