### ISSUE TITLE
[Feature] Support the same filter syntax as GitHub Workflows

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [tj-actions/changed-files#264]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

This action would be more intuitive and easier to use if it supported the same file filtering syntax as GitHub Workflows support natively. I realize the reason it does not is because it's easier to just accept the input that is used natively by the underlying bash commands. But I'm curious if this is something that could eventually be implemented.

### Describe the solution you'd like?

Use syntax like `foo/**/bar` instead of `^foo/.*/bar`, or `**/*.md` instead of  or `\.md$`. Exclusion rules could either be supported with `!` rules, or in a separate input (e.g. `exclude-files`).

### Anything else?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@solarmosaic-kflorence This should now be available in the latest release. Thanks
