### ISSUE TITLE
[Feature] Make it easier to exclude files

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [tj-actions/changed-files#265]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Right now `files` can be used to easily match files, essentially an "allow" list. For example, you can match any file which begins with a path, like `^path/to/directory`. However, it's not easy to exclude files. For example, if I wanted to match on all files in the `path/to/directory` except files which end with `.md`.

### Describe the solution you'd like?

It may be easiest to accept another input, such as `exclude-files`, which will simply be negated versions of the provided GREP regular expressions. For example, to exclude all files ending with `.md` you could do `exclude-files: \.md$`

### Describe alternatives you've considered?

See also: https://github.com/tj-actions/changed-files/issues/264 -- which if implemented could invalidate this ticket.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@solarmosaic-kflorence This should now be available in the latest release. Thanks
