### ISSUE TITLE
[Feature] Add "any_modified", "other_modified_files" and "all_modified" outputs containing created, edit, renamed, or deleted files

### ISSUE THREAD

**Issue by ashrafgt** [tj-actions/changed-files#282]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

In order to test for changes of any kind (create, edit, rename, delete), a combination of 2 conditions is required, like:
```yaml
if: ${{ steps.changed-files-specific.outputs.any_changed == 'true' || steps.changed-files-specific.outputs.any_deleted == 'true' }}
```

This works well, but it's a bit too long and could be simplified into a single expression.

### Describe the solution you'd like?

If possible, add 2 new outputs `any_touched` or `all_touched` which let the user check for any type of modification to the repository contents.  Something like:
```yaml
if: ${{ steps.changed-files-specific.outputs.any_touched == 'true' }}
```

### Describe alternatives you've considered?

Using two conditions with an OR operator, as described in the beginning.

### Anything else?

Gitlab CI's [`only:changes` clause](https://docs.gitlab.com/ee/ci/yaml/#onlychanges--exceptchanges) behaves similarly to what I'm requesting.

An example of why these variables might be useful is when running test jobs. If the commit only has changes to the README, test jobs could be skipped since no `.py` files were touched.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@ashrafgt This should now be available in the latest release.

Usage:

```yml
if: steps.changed-files-specific.outputs.any_modified == 'true'
```
