### ISSUE TITLE
Breaking changes in patch updates?

### ISSUE THREAD

**Issue by BaileyJM02** [tj-actions/changed-files#288]
Hello, due to a recent update this broke one of my CI pipelines. It appears in version [**1.1.4**](https://github.com/tj-actions/changed-files/releases/tag/v1.1.4) and [**1.1.1**](https://github.com/tj-actions/changed-files/releases/tag/v1.1.1) you included a breaking change. Please follow [semantic versioning](https://semver.org) to prevent this in the future.

**Comment by jackton1** [comment]
@BaileyJM02  Thanks for the suggestion. I'll recommend switching from the `v1.1.x` version to `v*` or `v*.*` semantics the legacy `1.1.x` was introduced earlier and wouldn't be supported longer term.


`v1.1.x` -> `v12`

### See
- https://github.com/tj-actions/changed-files/issues/79

> NOTE: Patch/Minor version v*.* aren't currently used by the corresponding major version which might change in the future.
