### ISSUE TITLE
[Feature] files-ignore

### ISSUE THREAD

**Issue by jacobrask** [tj-actions/changed-files#366]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Similar to `paths-ignore`, a property that lets you say "care about changes to any files but these files" would be useful in a monorepo scenario where you want to exclude certain paths.

### Describe the solution you'd like?

A new `files-ignore` property that is mutually exclusive with `files`. Files in `files-ignore` will never be reported as changed.

### Describe alternatives you've considered?

I could possibly use `files` with `['*', '!ignoredfiles']` but it quickly becomes complex.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@jacobrask This should be available in the latest release.

**Comment by jacobrask** [comment]
Fantastic, thank you!

**Comment by jackton1** [comment]
@jacobrask If you haven't already don't forget to star this project to help us reach a wider audience.
