### ISSUE TITLE
[BUG] It looks like no value such as any_changed has been written.

### ISSUE THREAD

**Issue by fagai** [tj-actions/changed-files#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

It looks like no value such as any_changed has been written.

### To Reproduce

https://github.com/tj-actions/changed-files/runs/5249951780?check_suite_focus=true
Check the execution result of "Show Output".

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

"any_changed": "true"

### Anything else?

If it's not a bug, how do I get true?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Based on the docs `any_changed` wouldn’t be set to `true|false` until you provide a list of files.

See: https://github.com/tj-actions/changed-files/runs/5249951780?check_suite_focus=true#step:5:36
