### ISSUE TITLE
[BUG] Separator `\n` only outputs first changed file

### ISSUE THREAD

**Issue by atorrescogollo** [tj-actions/changed-files#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When using `separator: "\n"`, only the first line is kept in the step output.

### To Reproduce

1. Use `separator: "\n"` with multiple changed files (more than one).
2. Echo the output from the next step.
3. In the latest step, you will only see the first changed file.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Using `separator: "\n"` should set output correctly and retrieve all changed files, not only the first one.

### Relevant log output

```shell
# -- STEP 1 --
> changed-files
... 
  All changed files: .terraform.lock.hcl
  testfolder with spaces/.terraform.lock.hcl
  testfolder1/.terraform.lock.hcl
  ...

# -- STEP 2 --
> echo "$CHANGED_FILES"
.terraform.lock.hcl
```

### Anything else?

I think this can solve the problem: https://github.community/t/set-output-truncates-multiline-strings/16852/3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@atorrescogollo I’m a little skeptical about using url encode values to replace the separator as not all downstream usage would decode the output.

**Comment by jackton1** [comment]
@atorrescogollo This should be available in the latest release.
