### ISSUE TITLE
[BUG] Argument too long

### ISSUE THREAD

**Issue by genieai-vikas** [tj-actions/changed-files#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Objective: I am trying to find if any files inside dir a,b,c is changed, added, deleted or modified if yes then I should get `true` and if not then `false`.

Right now facing 3 issues:
1. Changing the file of `dir a` but still getting false when using `steps.be_changed_files.outputs.only_changed`
2. when pipeline triggers from `synchronize` in `pull request`. The comparison is happening between the target branch's last commit and the current branch's latest commit. My expectation was to compare the file between the previous commit and the current commit of my current branch even in the pull request. 
3. When I use v17.2. I am getting an error
`Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/app/ui'. Argument list too long`

### To Reproduce

```
      - name: check if dir changed
        uses: tj-actions/changed-files@v17
        id: dir_changed_files
        with:
          files: |
            "src/microservices/a/**"
            "src/microservices/b/**"
            "src/microservices/c/**"
      - name: test
        run: |
            echo ${{ steps.be_changed_files.outputs.only_changed }}
```
when I am using v9.3 and changing a file inside `dir a`. I still get `false` 
when I use v17.2. I am getting an error
`Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/app/ui'. Argument list too long`

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I should get true if any files inside `dir a,b,c` is changed, added, deleted, or modified if yes then I should get `true` and if not then `false`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@genieai-vikas Answers to your questions:

> Changing the file of dir a but still getting false when using steps.be_changed_files.outputs.only_changed ?

Due to the fact that you're trying to figure out if only those files in the files list have changed. I'll recommend using `any_modified` output which would be true when any of the files have changed as opposed to `only_changed` which would be false if the PR contains other file changes.


> when pipeline triggers from synchronize in pull request. The comparison is happening between the target branch's last 
> commit and the current branch's latest commit. My expectation was to compare the file between the previous commit and > the current commit of my current branch even in the pull request.

This can be solved by using `since_last_remote_commit` set to `'true'`

See: https://github.com/tj-actions/changed-files#inputs

> When I use v17.2. I am getting an error 
> Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/app/ui'. Argument > list too long

From the usage above you're using v17 as opposed to v17.2 also the log output you posted doesn't capture the entire error, I'll recommend downloading the logs or copying all relevant logs associated to the `changed-files` action.

**Comment by genieai-vikas** [comment]
@jackton1 As you suggested I tested with this:

```
      - name: check if dir changed
        uses: tj-actions/changed-files@v17.2
        id: be_changed_files
        with:
          since_last_remote_commit: "true"
          files: |
            "src/microservices/a/**"
            "src/microservices/b/**"
            "src/microservices/c/**"
      - name: test
        run: |
            echo ${{ steps.be_changed_files.outputs.any_modified }}
```
echo ${{ steps.be_changed_files.outputs.any_modified }} is not returning any value. It's coming as blank even when I updated 2 files in the `src/microservices/a/`

Also, `any_modified`  will come `true` when any of the files inside dir a,b and c is changed only. If other files is changed this will come as false. right?

**Comment by jackton1** [comment]
Can you post the full log output ?

**Comment by jackton1** [comment]
Closing this as it appears to be a usage issue.

**Comment by genieai-vikas** [comment]
@jackton1 

Repo is private so I have removed some sensitive information:

```
Run tj-actions/changed-files@v17.2
  with:
    since_last_remote_commit: true
    files: "src/microservices/automation-test/**"
  "src/microservices/auth/**"
  "src/microservices/eadministrator/**"
  "src/microservices/eanalytics/**"
  "src/microservices/eauth/**"
  "src/microservices/ecommunity/**"
  "src/microservices/edataloader/**"
  "src/microservices/edocument/**"
  "src/microservices/eeditor/**"
  "src/microservices/eeditorauthority/**"
  "src/microservices/egateway/**"
  "src/microservices/eimage/**"
  "src/microservices/emarketplace/**"
  "src/microservices/etemplate/**"
  "src/microservices/testsuite/**"
  "src/microservices/euser/**"
  
    token: ***
    separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: 12e89940ffbaee01ab30b312aa282ab67430a387
    use_fork_point: false

Run # "Set base sha..."
  # "Set base sha..."
  if [[ -n "" ]]; then
    echo "::set-output name=base_sha::"
  elif [[ "true" == "true" && "e064b787a94c8756447ae5f37e3d26275160f1a3" != "0000000000000000000000000000000000000000" ]]; then
      echo "::set-output name=base_sha::e064b787a94c8756447ae5f37e3d26275160f1a3"
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

changed-files-diff-sha
  Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  Getting HEAD SHA...
  remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0        
  From 
   * branch                e064b787a94c8756447ae5f37e3d26275160f1a3 -> FETCH_HEAD
  Verifying commit SHA...
Run tj-actions/glob@v7
  with:
    files: "src/microservices/automation-test/**"
  "src/microservices/auth/**"
  "src/microservices/eadministrator/**"
  "src/microservices/eanalytics/**"
  "src/microservices/eauth/**"
  "src/microservices/ecommunity/**"
  "src/microservices/edataloader/**"
  "src/microservices/edocument/**"
  "src/microservices/eeditor/**"
  "src/microservices/eeditorauthority/**"
  "src/microservices/egateway/**"
  "src/microservices/eimage/**"
  "src/microservices/emarketplace/**"
  "src/microservices/etemplate/**"
  "src/microservices/testsuite/**"
  "src/microservices/euser/**"
  
    files-separator: 
  
    excluded-files-separator: 
  
    base-sha: e064b787a94c8756447ae5f37e3d26275160f1a3
    sha: 12e89940ffbaee01ab30b312aa282ab67430a387
    include-deleted-files: true
    separator: |
    files-from-source-file-separator: 
  
    excluded-files-from-source-file-separator: 
  
    follow-symbolic-links: true
    strip-top-level-dir: true

/usr/bin/git rev-parse --show-toplevel
/home/runner/work/app/app
/usr/bin/git diff --diff-filter=D --name-only e064b787a94c8756447ae5f37e3d26275160f1a3 12e89940ffbaee01ab30b312aa282ab67430a387
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
changed-files
  Resolving repository path...
  Retrieving changes between e064b787a94c8756447ae5f37e3d26275160f1a3 (remotes/origin/feature/github-conditional-build~1) → 12e89940ffbaee01ab30b312aa282ab67430a387 (feature/github-conditional-build)
  Getting diff...
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: .github/workflows/build-ci.yml
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: .github/workflows/build-ci.yml
  All changed files: .github/workflows/build-ci.yml
  All modified files: .github/workflows/build-ci.yml
```

**Comment by genieai-vikas** [comment]
This is the GitHub action I am using 

```
      - name: check if BE MS changed
        uses: tj-actions/changed-files@v17.2
        id: be_changed_files
        with:
          since_last_remote_commit: true
          files: |
            "src/microservices/automation-test/**"
            "src/microservices/auth/**"
            "src/microservices/eadministrator/**"
            "src/microservices/eanalytics/**"
            "src/microservices/eauth/**"
            "src/microservices/ecommunity/**"
            "src/microservices/edataloader/**"
            "src/microservices/edocument/**"
            "src/microservices/eeditor/**"
            "src/microservices/eeditorauthority/**"
            "src/microservices/egateway/**"
            "src/microservices/eimage/**"
            "src/microservices/emarketplace/**"
            "src/microservices/etemplate/**"
            "src/microservices/testsuite/**"
            "src/microservices/euser/**"
      - name: test
        run: |
            echo ${{ steps.be_changed_files.outputs.any_modified }
```

but I am getting blank value of ${{ steps.be_changed_files.outputs.any_modified }.

**Comment by jackton1** [comment]
You mentioned 

> when pipeline triggers from synchronize in pull request. The comparison is happening between the target branch's last 
> commit and the current branch's latest commit. My expectation was to compare the file between the previous commit and > the current commit of my current branch even in the pull request.

> This can be solved by using `since_last_remote_commit` set to `'true'`

From the lines above what happened is that you said I only want to know what changed since my last commit and all that changed was `.github/workflows/build-ci.yml` which doesn't appear in the list of `file` hence why you are getting an empty output. 

If you want it to be true for the PR i.e using the last commit on main and the current HEAD you'll need to remove the setting above.

**Comment by genieai-vikas** [comment]
@jackton1 I think I was not able to convey my use case. 

In a PR, there is always a target branch and a current branch. I just want to compare the last commit and current commit of my `current` branch (I don't care about the target branch) and if any of the files in the above-mentioned directories are changed, delete, or added. I want a `true` or `false` flag (`like this ${{ steps.be_changed_files.outputs.any_modified }`)so I can put a condition on my later steps.

**Comment by jackton1** [comment]
You might need to change 
```
${{ steps.be_changed_files.outputs.any_modified }
```
TO
```
${{ steps.be_changed_files.outputs.any_modified }}
```

**Comment by jackton1** [comment]
To debug the action you can use 

```yml
     - name: Show output
        run: |
          echo "${{ toJSON(steps.be_changed_files.outputs) }}"
        shell:
          bash
```

**Comment by genieai-vikas** [comment]
@jackton1 I am using `${{ steps.be_changed_files.outputs.any_modified }}`; I made copy-paste error above . Here is the output

```
{
  added_files: ,
  copied_files: ,
  deleted_files: ,
  modified_files: .github/workflows/build-ci.yml src/microservices/eeditor/Dockerfile,
  renamed_files: ,
  type_changed_files: ,
  unmerged_files: ,
  unknown_files: ,
  all_changed_and_modified_files: .github/workflows/build-ci.yml src/microservices/eeditor/Dockerfile,
  all_changed_files: .github/workflows/build-ci.yml src/microservices/eeditor/Dockerfile,
  any_changed: ,
  only_changed: ,
  other_changed_files: ,
  all_modified_files: .github/workflows/build-ci.yml src/microservices/eeditor/Dockerfile,
  any_modified: ,
  only_modified: ,
  other_modified_files: ,
  any_deleted: ,
  only_deleted: ,
  other_deleted_files: 
}
```

**Comment by jackton1** [comment]
Can you remove the quotes you have in the file paths

**Comment by genieai-vikas** [comment]
@jackton1 If I remove the quotes and run. I get this error

```
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/app/app'. Argument list too long
```

**Comment by jackton1** [comment]
How many files do you have in the repository?

**Comment by genieai-vikas** [comment]
@jackton1 I don't know but it's will grow for sure. Others are having the same issue as well.
https://github.com/tj-actions/changed-files/issues/367#issuecomment-1058270304

**Comment by jackton1** [comment]
I've reopened the old issue since this seems to be an external limit of the list of files passed to the action and would require some rework.

**Comment by genieai-vikas** [comment]
@jackton1 I think there is a new bug in v18 and v18.3. The below code was working fine in 17.3 but not anymore

```
      - name: Check condition for migration
        uses: tj-actions/changed-files@v17.3
        id: changed-files-specific
        with:
          base_sha: ${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}
          files: |
           src/microservices/ecommunity/**
            src/microservices/eimage/**
            helm/**
```

Description: I was passing **base_sha** so I can compare the current commit with the specific commit of a current branch. In v17.3, I can confirm it was working fine. Here is the output this is the `base_sha` I passed `6fbaee054706cfe09dbd3330e494ffc4fdb3a182` and this is the current `sha` 92774edb6ac6d323cdf3r74f1e3a8f8237bce051

```
changed-files
  Resolving repository path...
  Retrieving changes between 6fbaee054706cfe09dbd3330e494ffc4fdb3a182 (undefined) → 92774edb6ac6d323cdf3r74f1e3a8f8237bce051 (feature/add-skip-condition)
```

but in v18 and v18.3: even after passing `base_sha` it's comparing the target branch SHA and current branch SHA. here is the output 

```
changed-files
  Resolving repository path...
  Retrieving changes between c5b4bd7dat42eb959aa7be0fre059c88e86afe8f (develop) → 92774edb6ac6d3233df3f74f143a8f82472ce051 (feature/add-skip-condition)
```

**Comment by jackton1** [comment]
@genieai-vikas Can you file a new bug report highlighting your configuration and the output of the base_sha so I can take a look at this.

 Based on this diff [v17.3…v18.3](https://github.com/tj-actions/changed-files/compare/v17.3...v18.3) there wasn’t any change that should cause this bug. Thanks

**Comment by genieai-vikas** [comment]
Sure. I'll create a bug

**Comment by jackton1** [comment]
@genieai-vikas dont forget to include aall logs from tj-actions/changed-files and the output of `${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}`
