### ISSUE TITLE
[BUG] Glob Pattern Incorrect?

### ISSUE THREAD

**Issue by stumpylog** [tj-actions/changed-files#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When using the tj-actions/changed-files@v18.1 I do not see any files listed as being change.  The CI log also reports a warning about glob patterns that I suspect is related.

### To Reproduce

1. Make a commit with a change in a directory configured to be examined for changed files
2. Trigger the action
3. See no changed files listed

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The changed file should be listed.

### Relevant log output

```shell
Run tj-actions/changed-files@v18.1
Run # "Set base sha..."
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v7.8
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/paperless-ngx/paperless-ngx
/usr/bin/git diff --diff-filter=D --name-only bbe463b65760009411dd51d22ec4e8e1dbba89bd bbe463b65760009411dd51d22ec4e8e1dbba89bd
Warning: No match found for specified patterns. Ensure that subdirectory patterns a prefixed with "**/". See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
```

### Anything else?

Action steps:

              -
        name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.1
        with:
          files: |
            - src/**
      -
        name: List all changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "${file} was changed"
          done

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@stumpylog based on the yml configuration you have above you’ll need to remove hyphens `-` from the list of file patterns

**Comment by stumpylog** [comment]
Ah, it's using the some commit to do the diff:

`Retrieving changes between b5ae4e517ef1745472fe9cff1dce1772380b6bb8 (dev) → b5ae4e517ef1745472fe9cff1dce1772380b6bb8`

**Comment by jackton1** [comment]
Curious if this was a push event ?

**Comment by stumpylog** [comment]
Yes, with a fetch-depth=2, this worked.  I assume a pull_request event wouldn't need that.

So this was all user error.  Thanks for the info!
