### ISSUE TITLE
[BUG] Not able to compare current commit with the specific commit of a branch(in the Pull request event)

### ISSUE THREAD

**Issue by genieai-vikas** [tj-actions/changed-files#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I was passing base_sha so I can compare the current commit with the specific commit of a current branch. In v17.3, I can confirm it was working fine. Here is the output this is the base_sha I passed `6fbaee054706cfe09dbd3330e494ffc4fdb3a182` and this is the current sha `92774edb6ac6d323cdf3r74f1e3a8f8237bce051`

```
changed-files
  Resolving repository path...
  Retrieving changes between 6fbaee054706cfe09dbd3330e494ffc4fdb3a182 (undefined) → 92774edb6ac6d323cdf3r74f1e3a8f8237bce051 (feature/add-skip-condition)
```
but in v18 and v18.3: even after passing `base_sha` it's comparing the target branch SHA and current branch SHA. here is the output. The value of  ${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}} is  a891480e4a3927dd6e674e1d0bb50324f078da8a

```
changed-files
  Resolving repository path...
  Retrieving changes between c5b4bd7dat42eb959aa7be0fre059c88e86afe8f (develop) → 92774edb6ac6d3233df3f74f143a8f82472ce051 (feature/add-skip-condition)
```

Also, I also tried setting `since_last_remote_commit: "true"` but it's showing the wrong current SHA. I see this in Logs:

```
    INPUT_PREVIOUS_SHA: a891480e4a3927dd6e674e1d0bb50324f078da8a
    INPUT_CURRENT_SHA: dede7def9a1a77f620e24c33924c624292a15dd3
```
but actually, the `CURRENT_SHA` is `0f4593fb6411c7ad1be277bc0a9872953d2a3403`

As [er your comment "To your second point the sha you are seeing is a merge commit of the base branch into your PR branch which is why that’s different and it’s done by the checkout action." but this was not the case in `v17.3`

### To Reproduce

I think there is a new bug in v18 and v18.3. The below code was working fine in 17.3 but not anymore

```
      - name: Check condition for migration
        uses: tj-actions/changed-files@v17.3
        id: changed-files-specific
        with:
          base_sha: ${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}
          files: |
           src/microservices/ecommunity/**
            src/microservices/eimage/**
            helm/**
```

### What OS are you seeing the problem on?

macos-11

### Expected behavior?

I should be able to compare the latest commit of the current branch with the specific commit of the same branch(In pull request event)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@genieai-vikas can you provide the entire log output also include the exact value for `base_sha: ${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}`.

> Note: The default behavior is to use the last commit of the target branch only when the base_sha is empty. 

Can you also confirm that `${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}` is not empty ?

**Comment by jackton1** [comment]
@genieai-vikas based on this [test](https://github.com/tj-actions/changed-files/runs/5618892233?check_suite_focus=true#step:63:1) this doesn’t appear to be a bug. I’ll suggest double checking the output from the previous action.

**Comment by genieai-vikas** [comment]
@jackton1 I'll will double-check and let you know. 
Also, the test link you share I checked that link and saw your test jobs are terminating with exit code 1. Have you seen this 

![image](https://user-images.githubusercontent.com/86361824/159442015-68572df2-d4af-44a6-9e7a-07827a6d4a54.png)

![image](https://user-images.githubusercontent.com/86361824/159442166-d9cdc94c-80f5-4da0-977f-1dc81a4eb321.png)

**Comment by jackton1** [comment]
@genieai-vikas The link I shared redirects to this step in the logs 

![6631CA53-E8AB-4D11-BE62-1E754817D478](https://user-images.githubusercontent.com/17484350/159463904-a8a45c0f-da72-4980-b621-446f19a9a465.png)

![C81C2726-A43B-4E54-90DE-55EECED3FA50](https://user-images.githubusercontent.com/17484350/159464179-f189614d-cb19-4e8f-aada-08ada6668bd4.png)

the error you highlighted is coming from a failure test case i.e using a non existing hash

**Comment by genieai-vikas** [comment]
@jackton1  I checked again(with v18.4). Still, It does not show the expected behavior.
`${{needs.pre_ci.outputs.PREVIOUS_GITHUB_SHA}}` value is `dece9076331c0560e2dfef4a2a209a608a7474d2` 
  `Current SHA` value is `1f2e5f6658b50e110a4e817857d93da96af53173`
  
  
  Output logs:
  
```
  Run bash $GITHUB_ACTION_PATH/entrypoint.sh
  bash $GITHUB_ACTION_PATH/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_ACTION_PATH: /home/runner/work/_actions/tj-actions/changed-files/v18.4
    INPUT_FILES_PATTERN_FILE: /tmp/8b73bf4b-4b52-4653-a09d-74b4e02ec424.txt
    INPUT_SEPARATOR:  
    INPUT_PATH: 
    INPUT_PREVIOUS_SHA: c5b4bd7da342eb9f9aa7be0f5e059c88e86afe8f
    INPUT_CURRENT_SHA: 93bd3bfa44ef38f856b96c7aa8ed8b6d053ab6a3
    INPUT_TARGET_BRANCH: develop

Resolving repository path...
  Retrieving changes between c5b4bd7da342eb9f9aa7be0f5e059c88e86afe8f (develop) → 93bd3bfa44ef38f856b96c7aa8ed8b6d053ab6a3 (feature/add-skip-condition)
  Getting diff...
  Non Matching changed files: .github/workflows/build-ci.yml src/microservices/ecommunity/Dockerfile
  Matching modified files: src/microservices/eimage/docker/base/Dockerfile
  Non Matching modified files: .github/workflows/build-ci.yml src/microservices/ecommunity/Dockerfile
  Matching deleted files: src/microservices/eimage/docker/base/Dockerfile
  Added files: 
  Copied files: 
  Deleted files: src/microservices/eimage/docker/base/Dockerfile
  Modified files: 
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: src/microservices/eimage/docker/base/Dockerfile
  All changed files: 
  All modified files: src/microservices/eimage/docker/base/Dockerfile
```

**Comment by discordianfish** [comment]
I have the same issue. It looks like something causes it to use the wrong INPUT_CURRENT_SHA.

**Comment by discordianfish** [comment]
Ugh my issue was somewhere else and I tripped over INPUT_CURRENT_SHA being set to the local merge commit which of course isn't available in my local checkout. Anyway, seems to work fine for me.
