### ISSUE TITLE
[BUG] Intermittent "Unable to locate the current sha"

### ISSUE THREAD

**Issue by scottwn** [tj-actions/changed-files#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

On ~10% of runs, I see this output and the action fails.
```
Warning: Unable to locate the current sha: 0557cdadedb1fd4a763bb7306f3ab68c0ed1f8ca
Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
```
I have confirmed that I'm using `fetch-depth: 0`. 

### To Reproduce

I'm not able to reproduce the behavior. It seems to happen intermittently. Interestingly, when it _does_ happen, re-running the action fails with the same error. But I'm not sure what causes the initial failure.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I expect the action to be able to fetch history successfully.

### Relevant log output

```shell
Run tj-actions/changed-files@v18.4
  with:
    files: VERSION
  
    token: ***
    separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: 0557cdadedb1fd4a763bb7306f3ab68c0ed1f8ca
    since_last_remote_commit: false
    use_fork_point: false
Run # "Set base sha..."
  # "Set base sha..."
  if [[ -n "" ]]; then
    echo "::set-output name=base_sha::"
  elif [[ "false" == "true" && "ba0e94f9f5455cb3bf611a3bb9272c7bd7e07235" != "0000000000000000000000000000000000000000" ]]; then
      echo "::set-output name=base_sha::ba0e94f9f5455cb3bf611a3bb9272c7bd7e07235"
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: AgnostiqHQ/covalent
    GITHUB_BASE_REF: develop
    GITHUB_HEAD_REF: ci-fix
    GITHUB_ACTION_PATH: /home/runner/work/_actions/tj-actions/changed-files/v18.4
    INPUT_SHA: 0557cdadedb1fd4a763bb7306f3ab68c0ed1f8ca
    INPUT_BASE_SHA: 
    INPUT_TOKEN: ***
    INPUT_PATH: 
    INPUT_USE_FORK_POINT: false
changed-files-diff-sha
  Resolving repository path...
  Setting up 'temp_changed_files' remote...
  No 'temp_changed_files' remote found
  Creating 'temp_changed_files' remote...
  Getting HEAD SHA...
  Warning: Unable to locate the current sha: 0557cdadedb1fd4a763bb7306f3ab68c0ed1f8ca
  Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
  Error: Process completed with exit code 1.
```

### Anything else?

The workflow that uses the action: https://github.com/AgnostiqHQ/covalent/blob/develop/.github/workflows/version.yml
Example failed run: https://github.com/AgnostiqHQ/covalent/actions/runs/2059600589
Example successful run: https://github.com/AgnostiqHQ/covalent/actions/runs/2059933529

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@scottwn You might have to upgrade the checkout action as directed by the docs

**Comment by jackton1** [comment]
Some known conditions where this might happen:
1. Force push a commit which overrides the commit hash

2. Deleting a branch during the workflow execution.

**Comment by jackton1** [comment]
@scottwn looking at this workflow execution the previous step also fails since the commit no longer exists.

https://github.com/AgnostiqHQ/covalent/runs/5740169813?check_suite_focus=true#step:3:6

**Comment by dmohns** [comment]
Hey, I'm still encountering this issue. Although it looks a bit different to what was originally reported here. Should I create a new issue or post information here?

**Comment by jackton1** [comment]
@dmohns Sure

**Comment by dmohns** [comment]
Similar to the OP we encounter the issue 

```
  Warning: Unable to locate the previous sha: 
  Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
```

in an un-reproducible way. Sometimes rebasing and force-pushing fixes it, sometimes merging main fixes it. But also sometimes neither of them does.

The configuration I use is 

```
jobs:
  sqlfluff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          use_fork_point: "true"
```

Example error

```
  Resolving repository path...
  Getting HEAD SHA...
  Getting fork point...
  From https://github.com/***
   * [new branch]            main       -> main
  Verifying commit SHA...
  Warning: Unable to locate the previous sha: 
  Warning: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
  Error: Process completed with exit code 1.
```

Note how `previous sha` is empty. Unfortunately this happens in private repos and I cannot share the exact workflow run.

To investigate further I was wondering if there is a way to run this in "debug" mode? I.e. `set -x` somehow?

Steps taken so far:

- Ensure we are using latest Checkout action
- Double check no branches get deleted during workflow execution
- We sometimes force-push after rebases. But I don't think this should be related?

**Comment by dmohns** [comment]
I'll actually create a new issue for this, as after some investigation I think it's unrelated.
