### ISSUE TITLE
Not listing renamed file with previous path in deleted_files list

### ISSUE THREAD

**Issue by mansurhamidov14** [tj-actions/changed-files#466]
Expected to see renamed files with previous paths in the list of deleted_files. Is there any way to access previous file paths of renamed files?

**Comment by Steve-Groner** [comment]
I was just looking for this today as well.  I would hope that renamed files would show the original name so we can ensure any downstream actions are taken accordingly.

**Comment by jackton1** [comment]
@mansurhamidov14 This issue doesn’t follow the standard issue template. You can create a feature request using the issue template. Thanks

**Comment by mansurhamidov14** [comment]
> @mansurhamidov14 This issue doesn’t follow the standard issue template. You can create a feature request using the issue template. Thanks

I think I was clear enough. This is not corner case, this is one of the most common questions about which can be asked

**Comment by Steve-Groner** [comment]
A  properly formatted Feature Request has been added here https://github.com/tj-actions/changed-files/issues/467

**Comment by mansurhamidov14** [comment]
> A properly formatted Feature Request has been added here #467

I already subscribed. Thanks)
