### ISSUE TITLE
[Feature] Get distinct changed folders

### ISSUE THREAD

**Issue by mohitnayar123** [tj-actions/changed-files#504]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

We have build actions which consumes list of files which have changed, since the list of files can be very long, we are facing an error where the argument is too long, to fix the same, if we had a distinct list of changed folders we would be able to deal with this issue. 

### Describe the solution you'd like?

An option which outputs a list of changed folders.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@mohitnayar123 Any preference for reading the list of changed files from a temporary file which bypasses the character limitation of GitHub actions.

**Comment by choffa** [comment]
I would also like this feature, but for another reason:

We have a few repos that contains multiples microservices in seperate folders, or a backend service and a frontend in the same repo. Having an output with a list of changed directories would allow us to optimize running based on folders touched, saving time and compute.

**Comment by antimack** [comment]
+1 for a feature,  can be really useful in monorepo versioning

**Comment by jackton1** [comment]
@choffa @antimack @mohitnayar123 This is now available in the latest release.
