### ISSUE TITLE
[Feature] since_last_passing_remote_commit 

### ISSUE THREAD

**Issue by Archie-Elvie** [tj-actions/changed-files#507]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm currently using this action to detect changes to our dockerfile that we use for dev and our CI/CD pipeline. Currently it will rebuild our image and upload it to the registry if the dockerfile has changed since last remote commit. However, if the workflow fails before the build can be uploaded, this change in dockerfile is not captured.  Therefore the next remote commit that might fix the failed workflow might not have a dockerfile change and therefore the image rebuild will not take place and an old image will be used for testing. 

### Describe the solution you'd like?

A way to check if a file has been modified since the last passing remote commit. This should fix the issue stated above. Passing in this context is passing all enabled workflow checks. 

### Describe alternatives you've considered?

Current solution is a rule that disallows editing the workflows and dockerfile in the same remote commit, however other issues could arise (such as server failure) that this would not capture. 

### Anything else?

If anyone has a workaround for this that would work with the current version, that would be great. Let me know if you have any questions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@Archie-Elvie  I’ve update the [README](https://github.com/tj-actions/changed-files/README.md#examples) highlighting the solution to solving this problem.

**Comment by Archie-Elvie** [comment]
@jackton1 That works great, thank you. Out of interest is there a reason to use `tj-actions/branch-names@v5` instead of `${{ github.ref_name }}`?

**Comment by jackton1** [comment]
From my [test](https://github.com/tj-actions/branch-names/runs/6675552975?check_suite_focus=true#step:4:13) it doesn't appear that `${{ github.ref_name }}` is going to return a valid branch name always which is why `tj-actions/branch-names@v5` is recommended.
