### ISSUE TITLE
[BUG]  `files_ignore` glob pattern matching not behaving as expected

### ISSUE THREAD

**Issue by kencieszykowski** [tj-actions/changed-files#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

First off; this may be a misunderstanding of how this function is supposed to work; but for the life of me I can't seem to pattern match so that the files I want to ignore, are completely ignored.

### To Reproduce

      - name: Evaluate Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            config/*
          files_ignore: |
            .github/**

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I'm running a conditional in a separate job, keying off of `${{ steps.changed-files.outputs.only_changed }}`.

It successfully pulls the file changes from the directory, `config`, but the output listed above always gets flipped over to `false` when it notices any files changes within the `.github` folder.  

I would expect this to completely ignore any changes to files in the `.github` folder; and if there is only a change in one of the files in my `config` directory, then I would expect that `${{ steps.changed-files.outputs.only_changed }}` evaluates to `true`.

It's entirely possible I'm misunderstanding how these args interact with each other, but I would assume that a matching glob in the `files_ignore` key would not show up whatsoever; but they do show up in the output for `other_modified_files`, which I have to assume is what's causing my `only_changed` output to evaluate to `false`.

### Relevant log output

```bash
{
  "added_files": "",
  "copied_files": "",
  "deleted_files": "",
  "modified_files": "config/stage.yaml",
  "renamed_files": "",
  "all_old_new_renamed_files": "",
  "type_changed_files": "",
  "unmerged_files": "",
  "unknown_files": "",
  "all_changed_and_modified_files": "config/stage.yaml",
  "all_changed_files": "config/stage.yaml",
  "any_changed": "true",
  "only_changed": "false",
  "other_changed_files": ".github/workflows/pr.yaml .github/workflows/stage.yaml",
  "all_modified_files": "config/stage.yaml",
  "any_modified": "true",
  "only_modified": "false",
  "other_modified_files": ".github/workflows/pr.yaml .github/workflows/stage.yaml",
  "any_deleted": "false",
  "only_deleted": "",
  "other_deleted_files": ""
}
```

### Anything else?

I verified the glob pattern with [Glob Tester](https://globster.xyz).  Any help would be much appreciated.  This is a great little action and I'm hoping that I can be put on the right path here.  Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@kencieszykowski This seems like a difference in the expectation of the functionality.

`only_change`
```
Returns true when only 
files provided using 
the files input has changed. (ACMR)
```

Currently this works by comparing the set of changed files with the files-ignore pattern included to a set of the unfiltered changed files to determine if the sets are equal then return `true` else return `false` since the diff includes changes to other files.

You might want to use `any_changed` instead. 

```
Returns true when any 
of the filenames provided using 
the files input has changed. 
i.e. using a combination of all added, 
copied, modified and renamed files (ACMR)
```

I can see a case of excluding the files-ignore entirely from the list of changed files being compared but the functionality would potential break for others that rely on it.

**Comment by kencieszykowski** [comment]
@jackton1 

Thanks a lot for the clarity!  Apologies for filing this as a 'bug', I didn't see the option for 'question' when I submitted the request.

Appreciate your help on this matter, and love your Action!
