### ISSUE TITLE
[Feature]  implement an outputs for matrix compatible jobs

### ISSUE THREAD

**Issue by onedr0p** [tj-actions/changed-files#530]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hi 👋🏼 

It would be need if you had an `outputs` that can work with a matrix, this does not work

Check out this workflow: https://github.com/onedr0p/containers/blob/c15d8b71b288f812edb971a4c3966e62592bba1c/.github/workflows/release.yaml

And the run: https://github.com/onedr0p/containers/runs/6996087930?check_suite_focus=true

And the error: https://github.com/onedr0p/containers/actions/runs/2539358559

### Describe the solution you'd like?

Implement a `outputs.all_changed_files_json` or similar that can be used with `toJSON` and `fromJSON` to pass the outputs on to a matrix.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @onedr0p, based on the error
```
Error when evaluating 'strategy' for job 'release'. .github/workflows/release.yaml (Line: 44, Col: 15): Unexpected type of value 'images/lidarr/nightly/metadata.json', expected type: Sequence.
```

You seem to be passing a space-delimited string to the `toJSON` function without quotes.

```
outputs:
      matrix: "{\"container\": \"${{ toJson(steps.changed-files.outputs.all_changed_files) }}\" }"
```

> Note: You might also need to use the `separator` input to return a comma-separated string and wrap them in an array.

See: https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object

**Comment by jackton1** [comment]
@onedr0p Edited ⬆️

**Comment by SiddhantSadangi** [comment]
@jackton1 
I think the separator parameter is stripping out escaped double quotes:

Step:
```bash
    - name: Get changed notebooks
      id: changed-notebooks
      uses: tj-actions/changed-files@v23.1
      with:
        separator: "\", \""
        files: |
          **/*.ipynb
```

Code:
```bash
echo -e "Separator: \", \""
echo -e "Output: ${{ steps.changed-notebooks.outputs.all_changed_files }}"
echo -e "JSON format: {\"path\":[\"${{ steps.changed-notebooks.outputs.all_changed_files }}\""]}"
echo -e "::set-output name=changed_notebooks::{\"path\":[\"${{ steps.changed-notebooks.outputs.all_changed_files }}\""]}"
echo -e "JSON: ${{toJSON(needs.get-notebooks.outputs.changed_notebooks)}}"
```

Result:
```bash
Separator: ", "
Output: fail.ipynb, pass.ipynb
JSON format: {"path":["fail.ipynb, pass.ipynb"]}
echo -e ::set-output name=changed_notebooks::{"path":["fail.ipynb, pass.ipynb"]}
JSON: null
```

Expected result:
```bash
Separator: ", "
Output: fail.ipynb", "pass.ipynb
JSON format: {"path":["fail.ipynb", "pass.ipynb"]}
echo -e ::set-output name=changed_notebooks::{"path":["fail.ipynb", "pass.ipynb"]}
```

**Comment by sebestenyb** [comment]
Hi, I still have the error with the latest version:
```
Error when evaluating 'strategy' for job 'matrix-job'. .github/workflows/default.yml (Line: 30, Col: 15): Unexpected type of value '[\".github/workflows/default.yml\",\"demo.json\"]', expected type: Sequence.
```

I'm using the workflow file from the repository: https://github.com/tj-actions/changed-files/blob/dd1d85da10027d585a8e394aeee7524eb2f17bcf/.github/workflows/manual-matrix-test.yml

Even if I change the matrix definition in the workflow file to the one from above (`      matrix: "{\"container\": \"${{ steps.changed-files.outputs.all_changed_files }}\" }"`), the same error happens, slightly different output: 

```
Error when evaluating 'strategy' for job 'matrix-job'. .github/workflows/default.yml (Line: 30, Col: 15): Unexpected type of value '[".github/workflows/default.yml","demo.json"]', expected type: Sequence.
```

**Comment by jackton1** [comment]
@sebestenyb Note the lack of space between the key and value a full example of this can be seen here: https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object

**CHANGE**

```yml
matrix: "{\"container\": \"${{ steps.changed-files.outputs.all_changed_files }}\" }"
```

**TO** 

```yml
matrix:"{\"container\":${{ steps.changed-files.outputs.all_changed_files }}}"
```

See: https://github.com/tj-actions/changed-files/blob/main/.github/workflows/manual-matrix-test.yml#L27

**Comment by guitmz** [comment]
Actually what fixed for me was to specify 24.1 in my GitHub actions instead of only 24 for the version.
The syntax I grabbed from the repo test actions and it works fine!

**Comment by jackton1** [comment]
Cool.

**Comment by sebestenyb** [comment]
The latest test action in the repo is slightly different than the one in the PR merge commit above, it uses a separate step to set the matrix, like
```
- id: set-matrix
  run: echo "::set-output name=matrix::{\"container\":${{ steps.changed-files.outputs.all_changed_files }}}"
```

Not sure this fixed, or the lack of spaces, but it works now, thanks for you help folks!

**Comment by prein** [comment]
Would any of you mind posting full working example with passing the json to matrix strategy in another job?

**Comment by jackton1** [comment]
@prein Here’s an example: https://github.com/tj-actions/changed-files/blob/main/.github/workflows/manual-matrix-test.yml
