### ISSUE TITLE
[BUG] Repo name changed, workflows are broken

### ISSUE THREAD

**Issue by po5i** [tj-actions/changed-files#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

It seems the repo name changed from `changed-files` to `changed`. Now the for workflow to work it should be:

```
uses: tj-actions/changed@v23.1
```

All README occurrences should be changed. I can happily help with that if that is the only place to change the documentation. LMK.

### To Reproduce

1. Follow the existing documentation and the workflow outputs:

```
Getting action download info
Error: Unable to resolve actions. Repository not found: tj-actions/changed-files.
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Workflow should be executed as usual.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcus-crane** [comment]
Heya, +1ing this as we have a bunch of workflows that use this action and the repository name change has broken them all 😢

**Comment by jackton1** [comment]
@marcus-crane @po5i Sorry for the mix up I assumed GitHub would redirect request to the new name. Based on https://github.blog/2013-05-16-repository-redirects-are-here/ but it doesn’t appear to work for GitHub actions. The name change has been reverted.

Things should be back to normal. 🙏🏽
