### ISSUE TITLE
[BUG] changes based on last remote commit fail after rebasing

### ISSUE THREAD

**Issue by thearchitector** [tj-actions/changed-files#546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

A fairly common pattern in PRs is to rebase commits before merging, which might mean that the remote history gets erased/overwritten after a force push.

If the action is configured to calculate changes with `since_last_remote_commit: "true"`, the action fails after a rebase force push indicating the commit no longer exists.

### To Reproduce

1. Commit a few commits to a PR (`git commit` x 3 + `git push`)
2. Rebase and reword an old commit (`git rebase -i HEAD~3`)
3. Force push (`git push -f`)

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I would expect / hope for the last valid remote commit to get recalculated based on the commits overwritten in the rebase.

```
sha 01 (remote)
--
sha 23 (new)
sha 45 (new)

last_remote_commit = 01
```
after rebase:
```
sha 01 (remote)
--
sha 67 (new)
sha 89 (new)

last_remote_commit = 01 NOT 45
```

### Relevant log output

```bash
Error: Unable to locate the previous sha: 4242714b9997c0c6a32e6e0f7d9a25913d741360
Error: You seem to be missing 'fetch-depth: 0' or 'fetch-depth: 2'. See https://github.com/tj-actions/changed-files#usage
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@thearchitector This is now available in the latest release.
