### ISSUE TITLE
[Feature] Execute against master

### ISSUE THREAD

**Issue by wangwalton** [tj-actions/changed-files#556]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Looking to execute the diff against master changes, note that master may have changes that my branch doesn't have.

essentially looking for a way to do this, don't think it's possible, but please correct me if I'm wrong.
```
git diff --name-only master...HEAD
```

### Describe the solution you'd like?

Perhaps another input flag

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@wangwalton By adding the actions/checkout the master branch is already merged into your pull request branch. This action would return a diff of the last commit on master and your branch.

See: https://github.com/tj-actions/changed-files#usage

> NOTE: You’ll want to use a pull request event trigger

**Comment by wangwalton** [comment]
Would this work on the push event? Ideally I can have this feature before I make a pull request
