### ISSUE TITLE
[BUG] missing opening '(' then stop with windows-latest

### ISSUE THREAD

**Issue by sangshuduo** [tj-actions/changed-files#562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

My action's runs-on is windows-latest

the error message is:

 ParserError: D:\a\_temp\53945d85-e140-4e9e-baf5-4928a0b9745a.ps1:2
Line |
   2 |  for file in .github/workflows/windows.yml inc/bench.h src/CMakeLists. …
     |     ~
     | Missing opening '(' after keyword 'for'.

### To Reproduce

add following text to my script:

```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v24.1
        with:
          files: |
            src/*
            inc/*
            deps/CMakeLists.txt
            .github/workflows/windows.yml
```

run the workflow

### What OS are you seeing the problem on?

windows-latest or windows-2019

### Expected behavior?

work as what it work with linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@sangshuduo it appears there an unescaped characters in the filenames which is the cause of the error you are seeing. I'll recommend switching from bash loops to natively supported GitHub action function.

CHANGE
```
         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
```

TO
```
echo '${{ toJSON(steps.changed-files.outputs) }}'
```

**Comment by sangshuduo** [comment]
> @sangshuduo it appears there an unescaped characters in the filenames which is the cause of the error you are seeing. I'll recommend switching from bash loops to natively supported GitHub action function.
> 
> **CHANGE**
> 
> ```yaml
> for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
>   echo "$file was changed"
> done
> ```
> 
> **TO**
> 
> ```yaml
> echo '${{ toJSON(steps.changed-files.outputs) }}'
> ```
> 
> It would be helpful to also post the filename.

thanks. it works good.
