### ISSUE TITLE
[Feature] An option to include old names of renamed files in deleted_files array

### ISSUE THREAD

**Issue by anshulsahni** [tj-actions/changed-files#578]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I'm working on a GitHub action workflow where I need a list of all the deleted files, right now the deleted_files output includes only the files which are completely removed and excludes the ones which are renamed. In many cases such as mine[^1], old names of the renamed files are considered deleted and utilised as such.

Right now, as a workaround I'm using `include_all_old_new_renamed_files` flag I'm using `all_old_new_renamed_files` to get the old names of the renamed files and later both the lists are combined in the execution script, but that process is not that straight forward.

Firstly, I don't know why JSON option doesn't work on `all_old_new_renamed_files` array and everything is passed as one single string, then all different rename cases needs to be separated using the symbol passed as `old_new_files_separator` parameter, after that old & new named needs to be separated using symbol passed as `old_new_separator ` parameter

[^1]: Building documentation with docs as code, need to update search service (Algolia), about the pages which are removed from the content

### Describe the solution you'd like?

I would suggest the solution with the following design

1. An boolean input parameter like `include_old_renamed_in_deleted`
2. When the above parameter is passed with the value `true`, the deleted files and old names of the renamed files are given as a combined output variable
3. The renamed files can be combined in the deleted_files array parameter only or the output can be combined in a separate array

### Describe alternatives you've considered?

Right now the script utilising the deleted files list, I'm using the same script to combine two arrays of deleted files & renamed files into a single list. But the process is cumbersome as highlighted above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@anshulsahni Given the nature of this feature as described it sounds like you're on the right path. It would introduce complexity with little benefit. However, I can always circle back to implement it but the use case can be better handled in a separate action.

```yaml
run: |
   DELETED_AND_OLD_RENAMED_FILES=(${{...}} ${{...}})
```
