### ISSUE TITLE
[Feature] Publish `v29` release that redirects to the latest version within the major version

### ISSUE THREAD

**Issue by akihironitta** [tj-actions/changed-files#612]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

As we keep the action updated with the dependabot in our repository, we see the bot updates the action too frequently because there's no latest major version `v29`.

### Describe the solution you'd like?

I'd like you to publish the major version (`v29`) that always redirects to the latest patch version within the major version (`v29.0.3` as of now) just like other GH actions do, such as https://github.com/actions/checkout.

### Describe alternatives you've considered?

None

### Anything else?

(Completely off-topic, but FYI, the link to the Code of Conduct is invalid. I get the status code 406.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
This has been resolved. you should now be able to use the major version ([v29](https://github.com/tj-actions/changed-files/releases/tag/v29)) which would always include changes from any minor or patch versions going forward.
