### ISSUE TITLE
[Feature] Output changes to json files in filesystem for processing

### ISSUE THREAD

**Issue by neerup** [tj-actions/changed-files#688]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

No problem. Just a request :)

### Describe the solution you'd like?

Be able to have output to files

Use case:
I'm using a java program to process changed and deleted files in my workflow
So to be able to process the result from this action I use something like this
run: |
  echo "${{ steps.changed-files.outputs.added_files }}" >> "$HOME/added_files.json"
  echo "${{ steps.changed-files.outputs.copied_files }}" >> "$HOME/copied_files.json"
  echo "${{ steps.changed-files.outputs.deleted_files }}" >> "$HOME/deleted_files.json"
  ./mvnw -U -B -q compile exec:java --file ./pom.xml

Would really like to be able to have this action write the files for me.

Something like
Adding some new input parameters:

with:
  output_files: true // default false
  output_files_folder: $HOME // default $HOME
  json: true

Resulting in files being written to disk:
$HOME/added_files.json with json content of steps.changed-files.outputs.added_files
$HOME/deleted_files.json with json content of steps.changed-files.outputs.deleted_files
etc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@neerup This should be available in the latest release.
