### ISSUE TITLE
[BUG] Random GITHUB_OUTPUT: unbound variable in get-sha.sh

### ISSUE THREAD

**Issue by neerup** [tj-actions/changed-files#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Im getting random errors like this in my workflows on push
Rerunning the workflow usually resolves the problem

```
Run # "Calculate the sha..."
  # "Calculate the sha..."
  bash $GITHUB_ACTION_PATH/get-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64
    JAVA_HOME_8_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64
    GITHUB_WORKSPACE: /runner/_work/xxxx/xxxx
    INPUT_UNTIL: 
    INPUT_SHA: [43](https://github.com/****/actions/runs/3248434594/jobs/5329639214#step:6:45)94035c9769e1c5dcd7870ef4cb2ab4d5f7b996
    INPUT_PATH: .
/runner/_work/_actions/tj-actions/changed-files/v32/get-sha.sh: line 23: GITHUB_OUTPUT: unbound variable
Resolving repository path: /runner/_work/xxxx/xxxx/.
Error: Process completed with exit code 1.
```
[logs_505.zip](https://github.com/tj-actions/changed-files/files/9784351/logs_505.zip)

### To Reproduce

Self hosted runner

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Not to fail

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@neerup See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ 

Particularly if you are using self-hosted runners make sure they are updated to version 2.297.0 or greater.

**Comment by jackton1** [comment]
> @jackton1 I've seen a recent PR that switches to `$GITHUB_OUTPUT` and I saw it being appended to with double quotation marks, like `>> "$GITHUB_OUTPUT"`. Is this correct?
> 
> I'm pretty sure we're running >=2.298.2 in our self hosted runners.

Yes, the use of double quotation marks is valid and is used to prevent globbing or word splitting in shell scripts.

See: https://www.shellcheck.net/wiki/SC2086

**Comment by jackton1** [comment]
@neerup @mnmaita @cgooderham94 This should be resolved in the latest release. 

> **NOTE**: No action is required on your part as the changes are also available in the latest v32 major version.
