### ISSUE TITLE
Ability to do a three dots diff

### ISSUE THREAD

**Issue by erezrokah** [tj-actions/changed-files#702]
Hi 👋 Thank you for this great action 🚀 

On pull requests events it's quite useful to do a [three dots diff](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons), otherwise if the PR branch is not up to date with the base branch, the result of the diff is unexpected (changes are calculated from the top of the base branch so the output contains files not changed by the PR).

The fix would be to pass either `..` or `...` for all the diff commands, for example:
https://github.com/tj-actions/changed-files/blob/27c18b1c64f5fe93f03c72b5a849c899089b9039/get-changed-paths.sh#L27

If this makes sense I can submit a PR

**Comment by jackton1** [comment]
@erezrokah This is now available in the latest release.

**Comment by erezrokah** [comment]
Thanks @jackton1 for the super quick fix 🚀
