### ISSUE TITLE
[BUG] Fatal: $HOME not set

### ISSUE THREAD

**Issue by alfred-stokespace** [tj-actions/changed-files#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

```
Run bash $GITHUB_ACTION_PATH/get-changed-paths.sh
  bash $GITHUB_ACTION_PATH/get-changed-paths.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_WORKSPACE: /actions-runner/_work/REDACTED-REDACTED/REDACTED-REDACTED
    GITHUB_BASE_REF: main
    INPUT_FILES_PATTERN_FILE: /tmp/0658cf4a-97a5-4014-9815-d0efe86936c9.txt
    INPUT_SEPARATOR:  
    INPUT_PATH: .
    INPUT_PREVIOUS_SHA: dc96ac7ba9ca0443172c39b0d5bd545771927b52
    INPUT_CURRENT_SHA: db2490a6da9b81898355bce5389548cbd9e1492d
    INPUT_TARGET_BRANCH: main
    INPUT_CURRENT_BRANCH: feat/live-streaming-documentation
    INPUT_QUOTEPATH: true
    INPUT_INCLUDE_ALL_OLD_NEW_RENAMED_FILES: false
    INPUT_OLD_NEW_SEPARATOR: ,
    INPUT_OLD_NEW_FILES_SEPARATOR:  
    INPUT_DIFF_RELATIVE: 
    INPUT_DIR_NAMES: false
    INPUT_JSON: false
    INPUT_HAS_CUSTOM_PATTERNS: false
fatal: $HOME not set
Error: Process completed with exit code 128.
```

### To Reproduce

1. I'm running on an enterprise GH instance 3.5
2. I have a simple action copied from your example.  
    >``` 
    > - name: Get changed files
    >      id: changed-files
    >     uses: tj-actions/changed-files@v33
    > ```
4. When I try to trigger your action from a 
    > ```
    >   pull_request:
    >       types: [opened, reopened]
    > ```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Should have counted the files changed on my branch

### Relevant log output

```shell
Run bash $GITHUB_ACTION_PATH/get-changed-paths.sh
  bash $GITHUB_ACTION_PATH/get-changed-paths.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_WORKSPACE: /actions-runner/_work/REDACTED-REDACTED/REDACTED-REDACTED
    GITHUB_BASE_REF: main
    INPUT_FILES_PATTERN_FILE: /tmp/0658cf4a-97a5-4014-9815-d0efe86936c9.txt
    INPUT_SEPARATOR:  
    INPUT_PATH: .
    INPUT_PREVIOUS_SHA: dc96ac7ba9ca0443172c39b0d5bd545771927b52
    INPUT_CURRENT_SHA: db2490a6da9b81898355bce5389548cbd9e1492d
    INPUT_TARGET_BRANCH: main
    INPUT_CURRENT_BRANCH: feat/live-streaming-documentation
    INPUT_QUOTEPATH: true
    INPUT_INCLUDE_ALL_OLD_NEW_RENAMED_FILES: false
    INPUT_OLD_NEW_SEPARATOR: ,
    INPUT_OLD_NEW_FILES_SEPARATOR:  
    INPUT_DIFF_RELATIVE: 
    INPUT_DIR_NAMES: false
    INPUT_JSON: false
    INPUT_HAS_CUSTOM_PATTERNS: false
fatal: $HOME not set
Error: Process completed with exit code 128.
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@alfred-stokespace Given that the error is likely a misconfiguration I'll suggest you take a look at https://docs.github.com/en/enterprise-server@3.2/admin/installation/setting-up-a-github-enterprise-server-instance/installing-github-enterprise-server-on-aws#hardware-considerations, particularly noting that the AMI ID is correct.

**Comment by alfred-stokespace** [comment]
@jackton1 we have a ubuntu runner on site, are you suggesting I try that?

**Comment by alfred-stokespace** [comment]
hmm... I guess I took this as a suggestion `runs-on: ubuntu-latest  # windows-latest | macos-latest`
I'll give this a try on our ubuntu runner.

**Comment by alfred-stokespace** [comment]
Running on ubuntu didn't fix the issue, 
this did...
`echo "HOME=$(pwd)" >> $GITHUB_ENV`

like below

```
echo "HOME=$(pwd)" >> $GITHUB_ENV
  cat /etc/os-release
  shell: /usr/bin/bash -e {0}
NAME="Ubuntu"
VERSION="20.0[4](https://REDACTED/runs/28849?check_suite_focus=true#step:3:4).4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
....
```

**Comment by jackton1** [comment]
The question would be why isn't the HOME env set on the box, If you can take a look at the post generation script here https://github.com/actions/runner-images/tree/b7f276c003aea42575b52247bdb2183e355fca2f/images/linux/post-generation

**Comment by PLQin** [comment]
set:

```
export HOME="/home/ubuntu"
```

or

```
export HOME="/home/root"
```
