### ISSUE TITLE
Retrieve all changed files and directories relative to the last completed run of a GitHub Actions check

### ISSUE THREAD

**Issue by mwarres** [tj-actions/changed-files#735]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

In a project I'm working on, we have to generate a list of files that have been changed since the last completed run of a GitHub Actions check.  The code has already been written in a way that works for our project; I am happy to adapt it and add it to your project if it is something that would be helpful! I have permission to open-source the code. 

### Describe the solution you'd like?

The solution we used involves making a GraphQL query to return a list of the commits within the last 100 commits for which the  GitHub Actions checks have the status `"COMPLETED"`.  Then, we use a Python script to search those commits for runs with results `"SUCCESS"`, `"NEUTRAL"` or `"SKIPPED"` to determine the latest commit with completed, non-failing GitHub Actions checks.  Then we use `git diff` to determine the changed files.  

### Describe alternatives you've considered?

I considered porting our code from Python to Bash for consistency with the rest of your codebase.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@mwarres I believe that feature is already available using [nrwl/last-successful-commit-action](https://github.com/nrwl/last-successful-commit-action) as this isn't a core feature,  if you decide to open source the solution I'll suggest implementing it as a third party action and let me know how it goes.
