### ISSUE TITLE
Logical Issue in deepenShallowCloneToFindCommit 

### ISSUE THREAD

**Issue by hi-artem** [tj-actions/changed-files#747]
We have been using this action, and it periodically crashing while trying to deeper the shallow clone.

I am confused on the purpose of this loop:
https://github.com/tj-actions/changed-files/blob/58b52f3bf81ee4eeaf096bbaefe6415b85a706a0/diff-sha.sh#L78-L89

You can just deepen it to `max_fetch_depth`. AFAIK there are no performance benefits to deepening it multiple times.

Also with the current approach there is no way to reach the special depth of `2147483647`, which [according to docs](https://git-scm.com/docs/shallow) is infinite:
> The special depth 2147483647 (or 0x7fffffff, the largest positive number a signed 32-bit integer can contain) means infinite depth.

**Comment by jackton1** [comment]
This function has been removed
