### ISSUE TITLE
[Feature] Unique directories max_depth option

### ISSUE THREAD

**Issue by onedr0p** [tj-actions/changed-files#789]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hi 👋🏼  

It would be nice if the action supported a way to get set an option to the `dir_names` option which allow you to set a max depth to be unique.

#### A option of `dir_names_max_depth` which allows the level of paths to be unique

e.g. say you had a list of changes in this json array (`all_changed_files`) with `dir_names: true`

```json
[
  "infra/terraform/test/module_a/",
  "infra/terraform/test/module_b/",
  "infra/terraform/another_test/module_a/",
  "infra/terraform/another_test/module_b/"
  "infra/terraform/another_test/module_c/"
]
```

## Using the example above. output if `dir_names_max_depth: 2`

_this would omit the module folders_

```json
[
  "infra/terraform/test",
  "infra/terraform/another_test"
]
```

Where infra is path level `0`, terraform is `1` and test/another_test is `2`.

If `dir_names_max_depth` is not set or set too high it returns the whole path that `dir_names: true` would do now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by onedr0p** [comment]
Thanks @jackton1 ❤️

**Comment by jackton1** [comment]
@onedr0p Your welcome.
