### ISSUE TITLE
Should the Major Issue Version Point to the Latest Minor?

### ISSUE THREAD

**Issue by jmwyson** [tj-actions/changed-files#79]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to use the latest version of a specific major version in my pipeline. I would like to use the latest v5 version but comparing the latest commit hashes of v5.3 and v5, I see that these currently does not match. 

**Describe the solution you'd like**
It would be helpful if we can specify tj-actions/changed-files@v5 or tj-actions/changed-files@v5.x to mean to use latest v5 branch.

**Describe alternatives you've considered**
I am currently using tj-actions/changed-files@v5 in my action and only hope it gets pointed to the latest release.

**Additional context**
None

**Comment by jackton1** [comment]
@jmwyson Not sure that's supported yet, based on https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses you would need to specify the major.minor version to use the latest v5.3

**Comment by jackton1** [comment]
After reviewing https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management I agree that this should be the versioning process and I'll update all major versions to point to their relative latest minor/patch versions. Thanks @jmwyson

**Comment by jmwyson** [comment]
Thanks for reconsidering @jackton1!
