### ISSUE TITLE
`increase the fetch_depth to a number higher than 5000`

### ISSUE THREAD

**Issue by rainabba** [tj-actions/changed-files#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Even with `max_fetch_depth: 5000`, 

I'm getting: `Error: Unable to locate the current sha: *******************************
  Error: Please verify that current sha is valid, and increase the fetch_depth to a number higher than 5000.
  Error: Process completed with exit code 1.
`

### To Reproduce

This is on a private, enterprise repo so I can't reproduce publicly.  Our workflow in general is to branch from main to a feature/branch, then a PR setup against our QA branch. I'm seeing this on many of those pull-request runs.

### What OS are you seeing the problem on?

ubuntu-18.04

### Expected behavior?

A non-error outcome, or more useful value suggested.

### Relevant log output

```shell
# execution

Run tj-actions/changed-files@v34
  with:
    since_last_remote_commit: true
    dir_names: true
    fetch_depth: 5000
    separator:  
    include_all_old_new_renamed_files: false
    old_new_separator: ,
    old_new_files_separator:  
    files_separator: 
  
    files_ignore_separator: 
  
    sha: *******************************
    path: .
    quotepath: true
    json: false
    max_fetch_depth: 5000
```

# Output
```
Run # "Calculating the previous and current SHA..."
  # "Calculating the previous and current SHA..."
  bash $GITHUB_ACTION_PATH/diff-sha.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: my-org/my-repo
    GITHUB_REF: refs/pull/9531/merge
    GITHUB_BASE_REF: qa
    GITHUB_HEAD_REF: feature/my-new-feature
    GITHUB_WORKSPACE: /runner/_work/my-repo/my-repo
    GITHUB_EVENT_PULL_REQUEST_BASE_SHA: *******************************
    GITHUB_EVENT_BEFORE: 
    GITHUB_EVENT_FORCED: 
    INPUT_SHA: *******************************
    INPUT_BASE_SHA: 
    INPUT_SINCE: 
    INPUT_UNTIL: 
    INPUT_PATH: .
    INPUT_FETCH_DEPTH: 5000
    INPUT_MAX_FETCH_DEPTH: 5000
    INPUT_SINCE_LAST_REMOTE_COMMIT: true
changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.38.1)
  Running on a pull request event...
  Fetching remote refs...
  Error: Unable to locate the current sha: *******************************
  Error: Please verify that current sha is valid, and increase the fetch_depth to a number higher than 5000.
  Error: Process completed with exit code 1.
```
```


### Anything else?

Thanks for this Action. I'd written my own, but wasn't satisfied with the behavior (it seemed to be listing FAR too many changes), and this observation may be directly correlated with this error, but that's just a guy feel and I don't have a clear idea what/how to check as of yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rainabba** [comment]
Btw, the following is what I'm using for pull-requests (your action for everything else):

```
mapfile CHANGED_FILES < <(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/files | jq -r '.[].filename');
echo "CHANGED_FILES=${CHANGED_FILES[@]}" >> $GITHUB_ENV;
```

**Comment by jackton1** [comment]
High-level description: This bug occurs when the fork point and the last commit of the base branch have changed, resulting in errors finding the merge-base as the checkout action merges the tip of the target branch to the PR branch. 

To prevent this error going forward a pre-check to determine the validity of merge-base would be used falling back to the last commit of the target branch where necessary.

**Comment by rainabba** [comment]
Thanks for confirming the bug. To be clear, are you saying that I should setup that pre-check, or that will be added to the action [soon]? :D

**Comment by jackton1** [comment]
@rainabba This was already implemented in the latest release, I'll suggest you upgrade (if you use semver) or re-run the action (if you use the major version).
