### ISSUE TITLE
Unable to find merge-base between master and HEAD[BUG] <title>

### ISSUE THREAD

**Issue by davidbluevine** [tj-actions/changed-files#830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hey,
I ran github action with this action and I got:
 From https://github.com/arigosakiburi
   * [new branch]      master     -> origin/master
  branch 'master' set up to track 'origin/master'.
  From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  Error: Unable to find merge-base between master and HEAD.
  Error: Process completed with exit code 1.
  
  what can cause it?

### To Reproduce

.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

pass

### Relevant log output

```shell
From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  From https://github.com/arigosaki/buri
   * branch            master     -> FETCH_HEAD
   * branch            HEAD       -> FETCH_HEAD
  Error: Unable to find merge-base between master and HEAD.
  Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@davidbluevine Can you also provide the version you are using, based on the error I assume it isn’t the latest version.

**Comment by davidbluevine** [comment]
yes, I moved to the latest version and it solved it. Thanks!!!
I use using 34.3.4
