### ISSUE TITLE
[Feature] Deprecate usage of `set-output` command and upgrade to environment variable

### ISSUE THREAD

**Issue by ngdah** [tj-actions/changed-files#833]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

The workflow that uses `tj-actions/changed-files` action produces loads of warnings:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Describe the solution you'd like?

Change:
```
echo "::set-output name=name_of_output::value_of_output"
```
to
```
echo "name_of_outupt=value_of_output"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@ngdah Can you verify that your using the latest version as this issue has been resolved.

**Comment by ngdah** [comment]
yes, after using the latest `v34.5.0` the issue is confirmed to be fixed. thanks!
