### ISSUE TITLE
[BUG] Error: Unable to locate the previous sha: fatal: ambiguous argument 'main': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by valberg** [tj-actions/changed-files#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Since today I'm getting the following error:

>   Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: Unable to locate the previous sha: fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: Please verify that the previous sha commit is valid, and increase the fetch_depth to a number higher than 40.
  Error: Process completed with exit code 1.

I have tried setting the fetch-depth to 42 (higher than 40), with the same results.

I guess it has something to do with version 34.5.1 released yesterday.

### To Reproduce

Run changed-files with the latest version.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

I would expect it not to fail.

### Relevant log output

```shell
The log is too long for this input field so I have created a gist for it: https://gist.github.com/valberg/e2c48ae6dcee3794c33e70fd0857610a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@valberg This should resolve in the latest release.

**Comment by emesar** [comment]
I think this bug has recurred - potentially as a result of a `git pull origin main` on the target branch:
```
  Verifying git version...
  Valid git version found: (2.39.1)
  Running on a pull request event...
  fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
  Error: Unable to locate the previous sha: origin/main
  Error: Please verify that the previous sha is valid, and increase the fetch_depth to a number higher than 50.
  Error: Process completed with exit code 1.
```
