### ISSUE TITLE
[BUG] (v34.5.4) Input does not meet YAML 1.2 "Core Schema" specification: head-repo-fork

### ISSUE THREAD

**Issue by igotinfected** [tj-actions/changed-files#853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hey! After the `v34.5.4` release the actions I set up yesterday stopped working, with this error on the setup of the `changed-files` actions:

![image](https://user-images.githubusercontent.com/15004223/207179786-8c444196-d4d7-49ce-bfb1-1fac1c12c93d.png)

Replacing the `v34` pin with `v34.5.3` fixes this issue.

### To Reproduce

`.yml` provided in the links section.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

No error to appear with a minor release.

### Relevant log output

```shell
N.A. (can be added if required/necessary)
```

### Anything else?

Link to the `.yml`: https://github.com/igotinfected/gists/blob/main/.github/workflows/sync-changed-gists.yml

Link to the `actions`: https://github.com/igotinfected/gists/actions (e.g. https://github.com/igotinfected/gists/actions/runs/3680479483)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@igotinfected This has been resolved can you re-run the workflow?

**Comment by igotinfected** [comment]
Confirmed 👍
