### ISSUE TITLE
Changed lines of modified files

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [tj-actions/changed-files#858]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Why:
By providing the start and end of changed lines (chars) one can check some validations that only apply to the changed lines. 

### Use cases:
on a pull request, a github action will only check to see if developer has added a new inline disabled rule for eslint and create a comment to make it visible to reviewers that the pr includes disabled rules.

### Describe the solution you'd like?

I think the provided output should include the changed lines:
```js
modified_files_details   |   array<changeInfo>    |  [{file:string, type:modified | deleted | added, changes:[{startLine:number, endLine:number}]}]
```
Ex. 
```js
[ 
   {file:'package.json', type: 'modified', changes:[{startLine:2, endLine:5}, {startLine:13, endLine:15}]},
   {file:'package.json', type: 'added', changes:[{startLine:20, endLine:21}]}
]
```

or we can use file names as keys:
```js
modified_files_details   |  object    |  {fileName:[{ type:modified | deleted | added, changes:[{startLine:number, endLine:number}]}]}
```
Ex. 
```js
{ 
   'package.json': {type: 'modified', changes:[{startLine:2, endLine:5}, {startLine:13, endLine:15}]},
   'package.json': {type: 'added', changes:[{startLine:20, endLine:21}]},
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@ImanMahmoudinasab Thanks for your suggestion, given the complexity of managing the number of lines that can change in a Pull Request, at this time this wouldn't be possible without a more involved action so I'll recommend integrating a third-party solution which should be able to handle the complexity on a case-by-case basis.
