### ISSUE TITLE
[BUG] github actions has depreciated and will remove a feature used in this action 'set-output' see link 

### ISSUE THREAD

**Issue by don450p** [tj-actions/changed-files#865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Not currently a bug but upon the date of removal from actions it will become a breaking bug

### To Reproduce

Use the action: see depreciation messages
Search repo to see all instances of the depreciated github actions command
https://github.com/tj-actions/changed-files/search?q=set-output  

### What OS are you seeing the problem on?

all

### Expected behavior?

No depreciation message

### Relevant log output

```shell
Search of main showing this is still in use
https://github.com/tj-actions/changed-files/search?q=set-output


Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
```


### Anything else?


https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
quote
```
plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@don450p This has been resolved in the latest release. The error can be resolved by upgrading to [v34](https://github.com/tj-actions/changed-files/releases/tag/v34)

**Comment by donald-picard-kr** [comment]
Thanks, I am sorry for the mistake. I just figured out I was not on latest.
