### ISSUE TITLE
Request: Option to Output Whole File Path

### ISSUE THREAD

**Issue by merlinpatt** [tj-actions/changed-files#88]
**Is your feature request related to a problem? Please describe.**
I want to check if the file that's changed is in a specific directory.

**Describe the solution you'd like**
```
with:
  show_file_path: true
```

**Describe alternatives you've considered**
I could do `git status` and check within a `run:` block, but it seems like it would fit bettere as part of this action

**Additional context**
Sample output:
```
{
  added_files: Dockerfile src/components/Modal.jsx
  ...
}
```

**Comment by jackton1** [comment]
This is already supported the full path should be returned.

![Screen Shot 2021-06-03 at 1 16 31 AM](https://user-images.githubusercontent.com/17484350/120591012-6dc04900-c409-11eb-847c-4c4b0e32c279.png)

Let me know if there's a specific issue you're having

**Comment by merlinpatt** [comment]
The example in the readme only shows file names. Since paths are included, I think the example needs updating and this should be explicitly mentioned in the text as well.

**Comment by jackton1** [comment]
Okay would update the README to reflect that Thanks.

**Comment by jackton1** [comment]
Updated https://github.com/tj-actions/changed-files#changed-files to reflect those changes. 

Thanks @merlinpatt
