### ISSUE TITLE
[Feature] Output which file changed from files input

### ISSUE THREAD

**Issue by kemalgoklen** [tj-actions/changed-files#895]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

Hello,
Since the action has yet to have such a feature,  the overall workflow file is getting complex. Since I can only get a boolean from the output of files input, it does not bring any filtration over my files(it does, but I need to check the file contents as well and run more than one matrix based on file content and if it's changed or not). Along with getting any_changed = 'true | false', I'd love to have an exact filename like the all_changed_files output

### Describe the solution you'd like?

Along with getting any_changed = 'true | false', I'd love to have an exact filename like the all_changed_files output files_input_changed = 'filename'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@kemalgoklen  Can you provide more information on how you expect the feature to work ?

**Comment by kemalgoklen** [comment]
Hey, @jackton1 sure.
`      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect directories that contain terragrunthcl without dependency
        id: get_dirs
        run: |
           echo "$(find staging-acc -type f -name "terragrunt.hcl" -exec grep -R -i -L "dependency" {} \; | uniq)" >> dirs.txt

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files_from_source_file: dirs.txt
          files_ignore: |
            .github/**
          json: "true"
          dir_names: "true"
      - name: List all changed files
        run: |
          echo "All Changed ${{steps.changed-files-specific.outputs.all_changed_and_modified_files}}"
          echo " Other Changed ${{steps.changed-files-specific.outputs. any_changed}}"`
          As I mentioned, all changed files return all the changed files and any_changed will return a boolean value based on built dirs.txt.
          I expect to get which file has been changed in the provided source_file instead of getting a boolean value.

**Comment by jackton1** [comment]
I believe that information should already be available using the `all_changed_files` output.

See this line: https://github.com/tj-actions/changed-files/blob/main/get-changed-paths.sh#L208 which sets any_ changed to true or false.

Let me know if you have any other questions as this is already implemented.
