### ISSUE TITLE
[BUG] Unable to run on windows self-hosted runner

### ISSUE THREAD

**Issue by theotherp** [tj-actions/changed-files#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

When running on a windows self-hosted runner the diff calculation fails with `/bin/bash: G:actions-runner_work_tempbb000d1e-6179-4eea-9036-c406bb34d6df.sh: No such file or directory`.

See https://github.com/theotherp/nzbhydra2/actions/runs/3956707140/jobs/6776220258#step:23:64

It works on the github hosted runners so I'm not sure why this happens.

### To Reproduce

1. Have a windows self-hosted runner.
2. Use the action, I guess?

### What OS are you seeing the problem on?

all

### Expected behavior?

It works?

### Relevant log output

```shell
See link above.
```

### Anything else?

Ubuntu 22.04 WSL on Windows 10 located in `g:\actions-runner\`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by theotherp** [comment]
Hi. I ran it as a service and directly with admin privileges. G: or C: don't matter, they're both "normal" drives.

The problem is with the path `G:actions-runner_work_tempbb000d1e-6179-4eea-9036-c406bb34d6df.sh: No such file or directory.` which seems to be built using backslashes (`\`) but which are not properly escaped.

**Comment by jackton1** [comment]
In such a case I recommend filing an issue here https://github.com/actions/runner/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc instead.
