### ISSUE TITLE
[Feature] Exclude Files

### ISSUE THREAD

**Issue by SachinKainthSmarsh** [tj-actions/changed-files#963]
### Is this feature missing in the latest version?

- [X] I'm using the latest release

### Is your feature request related to a problem? Please describe.

I would like to see which files in a particular folder have been modified.  This much is already possible, but I would like to exclude a certain list of files within that folder from being reported on.  Plus, I only want to look at that folder and not in folders within that folder.

### Describe the solution you'd like?

I'd like to be able to not only specify a folder to monitor for changes but also 

1. Exclude certain files within that folder to be monitored for changes
2. Exclude all folders within that folder to be monitored for changes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @SachinKainthSmarsh I believe that is already supported.

You can prefix patttern passed to the files input with `!` or pass the patterns as is to the `files_ignore` input
