### ISSUE TITLE
[BUG] Unsynced target branch changes listed by action in pull requests

### ISSUE THREAD

**Issue by remisalmon** [tj-actions/changed-files#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

This a re-open of https://github.com/tj-actions/changed-files/issues/966 when this issue can be reproduced with the latest release.

### To Reproduce

See https://github.com/remisalmon/test-actions/pull/1/checks and https://github.com/remisalmon/test-actions/blob/main/.github/workflows/ci.yml: in the "Print changed files" step of the CI check only "b.txt" should be listed (the action is configured with files="*.txt" and "b.txt" is changed in the PR branch, but the actions lists both "a.txt" and "b.txt").

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Only files actually changed in the pull request branch should be listed by action, see https://github.com/remisalmon/test-actions/pull/1/files (in that case "b.txt").

### Relevant log output

```shell
See https://github.com/remisalmon/test-actions/pull/1/checks.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@remisalmon This should be resolved now.

**Comment by remisalmon** [comment]
> @remisalmon This should be resolved now. No action is required if you specify the major version but you'll need to bump to the latest patch version if you use the semantic version.

Yes thank you!
