### ISSUE TITLE
[BUG] Changes are retrieved for everything since initial commit, instead of the current context like the GitHub UI

### ISSUE THREAD

**Issue by hayescode** [tj-actions/changed-files#990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

I have an Action configured that runs when a PR is merged into Main. If my PR (1) was submitted before another PR (2), and the other PR (2) is merged 1st, this github action returns the changes from both PRs (1 and 2). I only want the changes from the PR that is running that action (1 in this example).

<pre>
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.4.1
        with:
          separator: ","
          quotepath: true
</pre>

I would expect to see these files in the Action but instead, I see considerably more, with no apparent way to differentiate which changes originated from where so that I could filter them out.

![image](https://user-images.githubusercontent.com/35790761/219370899-fefb3f82-9366-443d-8145-831e6fdbd37d.png)

### To Reproduce

1. Submit PR 1
2. Submit PR 2 
3. Merge # into main branch
4. Run changed-files on PR 1
5. File changes from both 1 and 2 are included

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Only the changed files in the PR are pulled in. Like how the GitHub UI does it.

### Relevant log output

```shell
Every file is change is pulled
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@hayescode I’ll recommend upgrading to the latest version, let me know if the issue persists and I’ll reopen this issue

**Comment by hayescode** [comment]
@jackton1 it's also happening on 35.5.5. Do I need to pull origin before running this action or something? It doesn't happen every time which make me think it's a bug.

**Comment by jackton1** [comment]
@hayescode Given the lack of much context, I’ll suggest creating a public repository the replicates the issue you are seeing.
