### ISSUE TITLE
action failed if path not matched

### ISSUE THREAD

**Issue by dongqiaoyang** [tj-actions/changed-files#992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

action fails if the path is not matched

### To Reproduce

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          json: true
          files: |
            /lab/**/Pulumi.yaml

input: 
lab folder does not exist  

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

action should not fail if path is not matched 

### Relevant log output

```shell
Error: No paths found using the specified patterns
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@dongqiaoyang I believe that’s expected which requires fixing the path pattern also consider removing the `/` in-front as the paths are relative to the working directory.

**Comment by dongqiaoyang** [comment]
@jackton1  Request to reopen it 

the removal of leading / did not solve the issue

Input: 
      - name: Get changed files empty
        id: changed-files-tj
        uses: tj-actions/changed-files@v35
        with:
          json: true
          files: |
            lab/**/Pulumi.yaml

Run tj-actions/changed-files@v35
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
Run tj-actions/glob@v16
/usr/bin/git rev-parse --show-toplevel
/home/runner/work/bi-watermelon/bi-watermelon
/usr/bin/git diff --diff-filter=D --name-only db1cc53e16d1c7a2a888e13866eef6574c22bd42..44dd85e2c8968bf3560bcd3648b67c5ca1cdf8cc
Error: No paths found using the specified patterns

**Comment by jackton1** [comment]
@dongqiaoyang In such a case I’ll suggest  creating a sample project that replicates the issue.

**Comment by dongqiaoyang** [comment]
What do you mean? the issue can just be replicated if you call the action on a non existing folder

**Comment by jackton1** [comment]
@dongqiaoyang Is there a particular reason why you want a pattern to match a non existing folder as this action only works with files that exists?

**Comment by pluveto** [comment]
Still not fix?

**Comment by jackton1** [comment]
What's not fixed?
