### ISSUE TITLE
[BUG] action fails when with a Git tag instead of branch

### ISSUE THREAD

**Issue by gpomykala** [tj-actions/changed-files#995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

action fails when pipeline is ran with a git tag rather than branch ie.
fatal: couldn't find remote ref refs/heads/v1.68.8
It most likely fails in 1 of these: 
https://github.com/tj-actions/changed-files/blob/main/diff-sha.sh#L63
https://github.com/tj-actions/changed-files/blob/main/diff-sha.sh#L173
https://github.com/tj-actions/changed-files/blob/main/diff-sha.sh#L223

### To Reproduce

i was able to reproduce locally on any repo with 
```shell
git fetch -u --progress origin +refs/heads/tag_name:refs/remotes/origin/tag_name 
```

### What OS are you seeing the problem on?

all

### Expected behavior?

should not crash

### Relevant log output

```shell
Run # "Calculating the previous and current SHA..."
changed-files-diff-sha
  Verifying git version...
  Valid git version found: (2.39.2)
  Running on a push event...
  Fetching remote refs...
  fatal: couldn't find remote ref refs/heads/v1.68.8
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@gpomykala This should be resolved in the latest release also note that the base_sha is now determined automatically and should only be set if you have a different use-case in which case be sure to fetch any prior history which includes the specific tag when using the default fetch-depth of the checkout action.
